# Generated by Django 4.2.7 on 2026-03-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentsubject'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studentsubject',
            new_name='students_st_student_2d5d24_idx',
            old_name='students_stu_student_6c7f98_idx',
        ),
        migrations.RenameIndex(
            model_name='studentsubject',
            new_name='students_st_subject_d7de22_idx',
            old_name='students_stu_subject_e2b339_idx',
        ),
    ]
