# Generated by Django 6.1.1 on 2026-09-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_students_stu_student_6c7f98_idx_students_st_student_2d5d24_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_sample_data',
            field=models.BooleanField(default=False, verbose_name='Is Sample Data'),
        ),
    ]
