# Generated by Django 4.2.7 on 2025-11-05 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Academic Year')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Holiday Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('holiday_type', models.CharField(choices=[('public', 'Public Holiday'), ('festival', 'Festival'), ('school', 'School Holiday'), ('optional', 'Optional Holiday')], max_length=20, verbose_name='Holiday Type')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['from_date'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=255, verbose_name='School Name')),
                ('school_code', models.CharField(blank=True, max_length=50, verbose_name='School Code')),
                ('school_email', models.EmailField(blank=True, max_length=254, verbose_name='School Email')),
                ('school_phone', models.CharField(blank=True, max_length=20, verbose_name='School Phone')),
                ('school_address', models.TextField(blank=True, verbose_name='School Address')),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='School Logo')),
                ('school_favicon', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='School Favicon')),
                ('promote_without_exam', models.BooleanField(default=False, verbose_name='Promote Students Without Exam')),
                ('date_format', models.CharField(default='DD-MM-YYYY', max_length=20, verbose_name='Date Format')),
                ('time_format', models.CharField(choices=[('12', '12 Hour'), ('24', '24 Hour')], default='12', max_length=10, verbose_name='Time Format')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Timezone')),
                ('currency_code', models.CharField(default='USD', max_length=10, verbose_name='Currency Code')),
                ('currency_symbol', models.CharField(default='$', max_length=5, verbose_name='Currency Symbol')),
                ('enable_online_admission', models.BooleanField(default=True, verbose_name='Enable Online Admission')),
                ('enable_email_notification', models.BooleanField(default=True, verbose_name='Enable Email Notifications')),
                ('enable_sms_notification', models.BooleanField(default=False, verbose_name='Enable SMS Notifications')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('session_timeout', models.IntegerField(default=30, verbose_name='Session Timeout (minutes)')),
                ('default_language', models.CharField(default='en', max_length=10, verbose_name='Default Language')),
                ('auto_backup', models.BooleanField(default=True, verbose_name='Auto Backup')),
                ('backup_time', models.TimeField(blank=True, null=True, verbose_name='Backup Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='Weekend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True, verbose_name='Day')),
                ('is_weekend', models.BooleanField(default=True, verbose_name='Is Weekend')),
            ],
            options={
                'verbose_name': 'Weekend',
                'verbose_name_plural': 'Weekends',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Priority')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'To-Do Item',
                'verbose_name_plural': 'To-Do List',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Session Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.academicyear')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20, verbose_name='Type')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Link')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('event_type', models.CharField(choices=[('meeting', 'Meeting'), ('exam', 'Examination'), ('holiday', 'Holiday'), ('event', 'Event'), ('reminder', 'Reminder'), ('other', 'Other')], max_length=20, verbose_name='Event Type')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('all_day', models.BooleanField(default=False, verbose_name='All Day Event')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is Public')),
                ('reminder_enabled', models.BooleanField(default=False, verbose_name='Reminder Enabled')),
                ('reminder_time', models.DurationField(blank=True, null=True, verbose_name='Reminder Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['start_date'],
            },
        ),
    ]
