# Generated by Django 5.2.7 on 2025-11-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='admission_number_prefix',
            field=models.CharField(default='STU', help_text='Prefix for auto-generated admission numbers (e.g., STU, AD, etc.)', max_length=10, verbose_name='Admission Number Prefix'),
        ),
    ]
