# Generated by Django 4.2.7 on 2025-12-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_admission_number_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='When enabled, only administrators can access the system.', verbose_name='Maintenance Mode'),
        ),
    ]
