# Generated by Django 4.2.7 on 2025-12-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemsetting_maintenance_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Email Notifications'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='parent_notifications',
            field=models.BooleanField(default=True, verbose_name='Parent Notifications'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='sms_notifications',
            field=models.BooleanField(default=True, verbose_name='SMS Notifications'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='teacher_notifications',
            field=models.BooleanField(default=True, verbose_name='Teacher Notifications'),
        ),
    ]
