# Generated by Django 4.2.7 on 2026-01-12 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_school_institution_type'),
        ('core', '0004_systemsetting_email_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='tenants.school'),
        ),
    ]
