# Generated by Django 4.2.7 on 2026-03-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='maintenance_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Maintenance End'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='maintenance_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Maintenance Start'),
        ),
    ]
