# Generated by Django 4.2.7 on 2026-03-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemsetting_maintenance_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='superadmin_only_mode',
            field=models.BooleanField(default=False, help_text='When enabled during maintenance, even school admins cannot login. Only super admins can access.', verbose_name='Super Admin Only Mode'),
        ),
    ]
