# Generated by Django 4.2.7 on 2026-03-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_systemsetting_superadmin_only_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='superadmin_maintenance_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Super Admin Maintenance End'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='superadmin_maintenance_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Super Admin Maintenance Start'),
        ),
    ]
