# Generated by Django 6.1.1 on 2026-09-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_systemsetting_superadmin_maintenance_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='accent_color',
            field=models.CharField(blank=True, default='#4DD0E1', max_length=20, verbose_name='Accent Color'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='primary_color',
            field=models.CharField(blank=True, default='#1E3A5F', max_length=20, verbose_name='Primary Color'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='secondary_color',
            field=models.CharField(blank=True, default='#2C5282', max_length=20, verbose_name='Secondary Color'),
        ),
    ]
