# Generated by Django 6.1.1 on 2026-09-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_systemsetting_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='default_navigation_layout',
            field=models.CharField(choices=[('sidebar', 'Vertical Sidebar'), ('horizontal', 'Horizontal Tabs')], default='sidebar', max_length=20, verbose_name='Default Navigation Layout'),
        ),
    ]
