# Generated by Django 6.1.1 on 2026-09-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_systemsetting_default_navigation_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='dark_accent_color',
            field=models.CharField(blank=True, default='#4DD0E1', max_length=20, verbose_name='Dark Mode Accent Color'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='dark_bg_color',
            field=models.CharField(blank=True, default='#0F172A', max_length=20, verbose_name='Dark Mode Background Color'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='dark_primary_color',
            field=models.CharField(blank=True, default='#38BDF8', max_length=20, verbose_name='Dark Mode Primary Color'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='dark_secondary_color',
            field=models.CharField(blank=True, default='#818CF8', max_length=20, verbose_name='Dark Mode Secondary Color'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='accent_color',
            field=models.CharField(blank=True, default='#38BDF8', max_length=20, verbose_name='Accent Color'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='primary_color',
            field=models.CharField(blank=True, default='#0284C7', max_length=20, verbose_name='Primary Color'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='secondary_color',
            field=models.CharField(blank=True, default='#475569', max_length=20, verbose_name='Secondary Color'),
        ),
    ]
