# Generated by Django 6.1.1 on 2026-09-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_systemsetting_dark_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='icon_color',
            field=models.CharField(blank=True, default='#0284C7', max_length=20, verbose_name='System Icon Color'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='dark_icon_color',
            field=models.CharField(blank=True, default='#38BDF8', max_length=20, verbose_name='Dark Mode Icon Color'),
        ),
    ]
