# Generated by Django 6.1.1 on 2026-09-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0003_department_school_designation_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_sample_data',
            field=models.BooleanField(default=False, verbose_name='Is Sample Data'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_sample_data',
            field=models.BooleanField(default=False, verbose_name='Is Sample Data'),
        ),
    ]
