# Generated by Cascade
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
from decimal import Decimal


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
        ('core', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Account Code')),
                ('name', models.CharField(max_length=200, verbose_name='Account Name')),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=20, verbose_name='Account Type')),
                ('sub_type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('receivable', 'Receivable'), ('payable', 'Payable'), ('other', 'Other')], default='other', max_length=20, verbose_name='Sub-Type')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Opening Balance')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='tenants.school')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['code'],
                'unique_together': {('school', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('fee_collection', 'Fee Collection'), ('donation', 'Donation Receipt'), ('payment', 'Payment'), ('reversal', 'Reversal')], max_length=30, verbose_name='Transaction Type')),
                ('date', models.DateField(verbose_name='Date')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Reference / Receipt No')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Amount')),
                ('is_advance', models.BooleanField(default=False, verbose_name='Is Advance (Fees)')),
                ('donor_name', models.CharField(blank=True, max_length=200, verbose_name='Donor Name')),
                ('donation_type', models.CharField(blank=True, choices=[('restricted', 'Restricted'), ('unrestricted', 'Unrestricted')], max_length=20, verbose_name='Donation Type')),
                ('payee_type', models.CharField(blank=True, choices=[('staff', 'Staff'), ('supplier', 'Supplier'), ('other', 'Other')], max_length=20, verbose_name='Payee Type')),
                ('payee_id', models.IntegerField(blank=True, null=True, verbose_name='Payee ID')),
                ('payee_name', models.CharField(blank=True, max_length=200, verbose_name='Payee Name')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='pending', max_length=20, verbose_name='Status')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Posted At')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to='core.academicyear')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finance_transactions', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_finance_transactions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_transactions', to='tenants.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_transactions', to='students.student')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-id'],
                'permissions': [('can_create_finance_transactions', 'Can create finance transactions'), ('can_post_finance_transactions', 'Can approve/post finance transactions')],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Reference')),
                ('memo', models.CharField(blank=True, max_length=255, verbose_name='Memo/Description')),
                ('posted', models.BooleanField(default=False, verbose_name='Posted')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Posted At')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_posted', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='tenants.school')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entry', to='finance.transaction')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Debit')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Credit')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='finance.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry')),
            ],
            options={
                'verbose_name': 'Journal Entry Line',
                'verbose_name_plural': 'Journal Entry Lines',
            },
        ),
    ]
