# Generated by Django 4.2.7 on 2026-01-19 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_journalentry_date_alter_transaction_date'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollection',
            name='deposit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_collections', to='finance.account'),
        ),
    ]
