# Generated by Django 4.2.7 on 2025-11-05 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='School Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal Code')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/', verbose_name='School Logo')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='Established Date')),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registration Number')),
                ('subscription_start_date', models.DateField(blank=True, null=True, verbose_name='Subscription Start Date')),
                ('subscription_end_date', models.DateField(blank=True, null=True, verbose_name='Subscription End Date')),
                ('is_trial', models.BooleanField(default=False, verbose_name='Is Trial')),
                ('trial_end_date', models.DateField(blank=True, null=True, verbose_name='Trial End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('max_students', models.IntegerField(default=100, verbose_name='Maximum Students')),
                ('max_teachers', models.IntegerField(default=20, verbose_name='Maximum Teachers')),
                ('max_staff', models.IntegerField(default=10, verbose_name='Maximum Staff')),
                ('academic_year_start_month', models.IntegerField(default=4, verbose_name='Academic Year Start Month')),
                ('date_format', models.CharField(default='DD-MM-YYYY', max_length=20, verbose_name='Date Format')),
                ('time_format', models.CharField(default='12', max_length=20, verbose_name='Time Format')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Currency')),
                ('currency_symbol', models.CharField(default='$', max_length=5, verbose_name='Currency Symbol')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Timezone')),
                ('enable_online_exam', models.BooleanField(default=True, verbose_name='Enable Online Exam')),
                ('enable_online_payment', models.BooleanField(default=True, verbose_name='Enable Online Payment')),
                ('enable_chat', models.BooleanField(default=True, verbose_name='Enable Chat')),
                ('enable_sms', models.BooleanField(default=True, verbose_name='Enable SMS')),
                ('enable_library', models.BooleanField(default=True, verbose_name='Enable Library')),
                ('enable_transport', models.BooleanField(default=True, verbose_name='Enable Transport')),
                ('enable_dormitory', models.BooleanField(default=True, verbose_name='Enable Dormitory')),
                ('enable_inventory', models.BooleanField(default=True, verbose_name='Enable Inventory')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True, verbose_name='Domain')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Is Primary')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.school')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
            },
        ),
    ]
