# Generated by Django 4.2.7 on 2025-12-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='institution_type',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('pre_primary_primary', 'Pre-Primary & Primary'), ('primary_junior_secondary', 'Primary & Junior Secondary'), ('junior_secondary_only', 'Junior Secondary Only'), ('senior_secondary', 'Senior Secondary'), ('tvet_college', 'TVET / College'), ('mixed', 'Mixed School (Multiple Levels)')], default='unspecified', max_length=50, verbose_name='Institution Type'),
        ),
    ]
