# Generated by Django 5.2.17 on 2026-10-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_school_institution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='subscription_plan',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='schools',
                to='subscriptions.subscriptionplan',
            ),
        ),
    ]
