# Generated by Django 6.1.1 on 2026-10-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_school_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='allow_system_ai',
            field=models.BooleanField(default=False, help_text="Allow this school to use the platform's central AI models as default", verbose_name='Allow System AI'),
        ),
        migrations.AddField(
            model_name='school',
            name='allow_system_email',
            field=models.BooleanField(default=False, help_text="Allow this school to use the platform's central Email gateway as default", verbose_name='Allow System Email'),
        ),
        migrations.AddField(
            model_name='school',
            name='allow_system_sms',
            field=models.BooleanField(default=False, help_text="Allow this school to use the platform's central SMS gateway as default", verbose_name='Allow System SMS'),
        ),
        migrations.AddField(
            model_name='school',
            name='allow_system_whatsapp',
            field=models.BooleanField(default=False, help_text="Allow this school to use the platform's central WhatsApp gateway as default", verbose_name='Allow System WhatsApp'),
        ),
    ]
