# Generated by Django 4.2.7 on 2026-01-12 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        ('tenants', '0002_school_institution_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('planned_date', models.DateField()),
                ('lesson_number', models.PositiveIntegerField(blank=True, null=True)),
                ('grade_level', models.CharField(blank=True, max_length=50)),
                ('unit_title', models.CharField(blank=True, max_length=200)),
                ('learning_objectives', models.TextField()),
                ('materials_resources', models.TextField(blank=True)),
                ('introduction', models.TextField(blank=True)),
                ('main_content', models.TextField()),
                ('activities', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('differentiation', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('homework', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('completed', 'Completed'), ('draft', 'Draft'), ('rejected', 'Rejected'), ('review', 'In Review')], default='draft', max_length=20)),
                ('is_executed', models.BooleanField(default=False)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('execution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='core.academicyear')),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='academics.class')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lesson_plans', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='tenants.school')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='academics.subject')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='lesson_plan.lessonplantemplate')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlanFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='lesson_plan.lessonplan')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlanResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('audio', 'Audio'), ('document', 'Document'), ('image', 'Image'), ('link', 'Web Link'), ('other', 'Other'), ('presentation', 'Presentation'), ('video', 'Video'), ('worksheet', 'Worksheet')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_plan_resources/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_lesson_resources', to=settings.AUTH_USER_MODEL)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='lesson_plan.lessonplan')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlanStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('standard_code', models.CharField(max_length=50)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='lesson_plan.lessonplan')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('structure', models.JSONField(default=dict)),
                ('template_type', models.CharField(choices=[('custom', 'Custom'), ('differentiated', 'Differentiated Instruction'), ('direct_instruction', 'Direct Instruction'), ('flipped_classroom', 'Flipped Classroom'), ('inquiry_based', 'Inquiry Based Learning'), ('project_based', 'Project Based Learning'), ('standard', 'Standard')], default='standard', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lesson_templates', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_templates', to='tenants.school')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
