# Generated by Django 4.2.7 on 2025-11-13 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('academics', '0004_class_school_subject_school'),
        ('core', '0002_add_admission_number_prefix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Lesson Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Duration (minutes)')),
                ('planned_date', models.DateField(verbose_name='Planned Date')),
                ('learning_objectives', models.TextField(verbose_name='Learning Objectives')),
                ('materials_resources', models.TextField(blank=True, verbose_name='Materials & Resources')),
                ('introduction', models.TextField(blank=True, verbose_name='Introduction')),
                ('main_content', models.TextField(verbose_name='Main Content')),
                ('activities', models.TextField(blank=True, verbose_name='Activities')),
                ('assessment', models.TextField(blank=True, verbose_name='Assessment')),
                ('differentiation', models.TextField(blank=True, verbose_name='Differentiation Strategies')),
                ('conclusion', models.TextField(blank=True, verbose_name='Conclusion')),
                ('homework', models.TextField(blank=True, verbose_name='Homework Assignment')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='lesson_plans/', verbose_name='Attachments')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='draft', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('is_executed', models.BooleanField(default=False, verbose_name='Is Executed')),
                ('execution_date', models.DateField(blank=True, null=True, verbose_name='Execution Date')),
                ('execution_notes', models.TextField(blank=True, verbose_name='Execution Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='core.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lesson_plans', to=settings.AUTH_USER_MODEL)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='academics.class')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lesson_plans', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Lesson Plan',
                'verbose_name_plural': 'Lesson Plans',
                'ordering': ['planned_date'],
            },
        ),
        migrations.CreateModel(
            name='LessonPlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('template_type', models.CharField(choices=[('standard', 'Standard'), ('project_based', 'Project Based Learning'), ('inquiry_based', 'Inquiry Based Learning'), ('direct_instruction', 'Direct Instruction'), ('flipped_classroom', 'Flipped Classroom'), ('differentiated', 'Differentiated Instruction'), ('custom', 'Custom')], default='standard', max_length=30, verbose_name='Template Type')),
                ('structure', models.JSONField(default=dict, verbose_name='Template Structure')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lesson_templates', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_templates', to='tenants.school')),
            ],
            options={
                'verbose_name': 'Lesson Plan Template',
                'verbose_name_plural': 'Lesson Plan Templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LessonPlanStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_code', models.CharField(max_length=50, verbose_name='Standard Code')),
                ('description', models.TextField(verbose_name='Standard Description')),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='lesson_plan.lessonplan')),
            ],
            options={
                'verbose_name': 'Lesson Plan Standard',
                'verbose_name_plural': 'Lesson Plan Standards',
            },
        ),
        migrations.CreateModel(
            name='LessonPlanResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Resource Title')),
                ('resource_type', models.CharField(choices=[('document', 'Document'), ('presentation', 'Presentation'), ('worksheet', 'Worksheet'), ('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('link', 'Web Link'), ('other', 'Other')], max_length=20, verbose_name='Resource Type')),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_plan_resources/', verbose_name='File')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_lesson_resources', to=settings.AUTH_USER_MODEL)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='lesson_plan.lessonplan')),
            ],
            options={
                'verbose_name': 'Lesson Plan Resource',
                'verbose_name_plural': 'Lesson Plan Resources',
            },
        ),
        migrations.CreateModel(
            name='LessonPlanFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='Feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='lesson_plan.lessonplan')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Plan Feedback',
                'verbose_name_plural': 'Lesson Plan Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='lesson_plan.lessonplantemplate'),
        ),
    ]
