# Generated by Django 4.2.7 on 2025-11-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='lesson_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lesson Number'),
        ),
    ]
