# Generated by Django 4.2.7 on 2026-01-12 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonplan',
            options={'ordering': ['planned_date'], 'verbose_name': 'Lesson Plan', 'verbose_name_plural': 'Lesson Plans'},
        ),
        migrations.AlterModelOptions(
            name='lessonplanfeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lesson Plan Feedback', 'verbose_name_plural': 'Lesson Plan Feedback'},
        ),
        migrations.AlterModelOptions(
            name='lessonplanresource',
            options={'verbose_name': 'Lesson Plan Resource', 'verbose_name_plural': 'Lesson Plan Resources'},
        ),
        migrations.AlterModelOptions(
            name='lessonplanstandard',
            options={'verbose_name': 'Lesson Plan Standard', 'verbose_name_plural': 'Lesson Plan Standards'},
        ),
        migrations.AlterModelOptions(
            name='lessonplantemplate',
            options={'ordering': ['-is_default', 'name'], 'verbose_name': 'Lesson Plan Template', 'verbose_name_plural': 'Lesson Plan Templates'},
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lesson_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='lesson_plans/', verbose_name='Attachments'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='activities',
            field=models.TextField(blank=True, verbose_name='Activities'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='assessment',
            field=models.TextField(blank=True, verbose_name='Assessment'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='conclusion',
            field=models.TextField(blank=True, verbose_name='Conclusion'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='differentiation',
            field=models.TextField(blank=True, verbose_name='Differentiation Strategies'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='execution_date',
            field=models.DateField(blank=True, null=True, verbose_name='Execution Date'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='execution_notes',
            field=models.TextField(blank=True, verbose_name='Execution Notes'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='grade_level',
            field=models.CharField(blank=True, max_length=50, verbose_name='Grade Level'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='homework',
            field=models.TextField(blank=True, verbose_name='Homework Assignment'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='introduction',
            field=models.TextField(blank=True, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='is_executed',
            field=models.BooleanField(default=False, verbose_name='Is Executed'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='learning_objectives',
            field=models.TextField(verbose_name='Learning Objectives'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='lesson_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lesson Number'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='main_content',
            field=models.TextField(verbose_name='Main Content'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='materials_resources',
            field=models.TextField(blank=True, verbose_name='Materials & Resources'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Additional Notes'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='planned_date',
            field=models.DateField(verbose_name='Planned Date'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Lesson Title'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='unit_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Unit Title'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='lessonplanfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='lessonplanfeedback',
            name='feedback',
            field=models.TextField(verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='lessonplanresource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='lessonplanresource',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='lessonplanresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_plan_resources/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='lessonplanresource',
            name='resource_type',
            field=models.CharField(choices=[('document', 'Document'), ('presentation', 'Presentation'), ('worksheet', 'Worksheet'), ('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('link', 'Web Link'), ('other', 'Other')], max_length=20, verbose_name='Resource Type'),
        ),
        migrations.AlterField(
            model_name='lessonplanresource',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Resource Title'),
        ),
        migrations.AlterField(
            model_name='lessonplanresource',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='lessonplanstandard',
            name='description',
            field=models.TextField(verbose_name='Standard Description'),
        ),
        migrations.AlterField(
            model_name='lessonplanstandard',
            name='standard_code',
            field=models.CharField(max_length=50, verbose_name='Standard Code'),
        ),
        migrations.AlterField(
            model_name='lessonplantemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='lessonplantemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lesson_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonplantemplate',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='lessonplantemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='lessonplantemplate',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is Default'),
        ),
        migrations.AlterField(
            model_name='lessonplantemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Template Name'),
        ),
        migrations.AlterField(
            model_name='lessonplantemplate',
            name='structure',
            field=models.JSONField(default=dict, verbose_name='Template Structure'),
        ),
        migrations.AlterField(
            model_name='lessonplantemplate',
            name='template_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('project_based', 'Project Based Learning'), ('inquiry_based', 'Inquiry Based Learning'), ('direct_instruction', 'Direct Instruction'), ('flipped_classroom', 'Flipped Classroom'), ('differentiated', 'Differentiated Instruction'), ('custom', 'Custom')], default='standard', max_length=30, verbose_name='Template Type'),
        ),
        migrations.AlterField(
            model_name='lessonplantemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
