# Generated by Django 4.2.7 on 2025-11-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plan', '0002_lessonplan_lesson_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='grade_level',
            field=models.CharField(blank=True, max_length=50, verbose_name='Grade Level'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='unit_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Unit Title'),
        ),
    ]
