# Generated by Django 4.2.7 on 2026-01-19 08:12

from django.conf import settings
from django.db import migrations, models, connection
import django.db.models.deletion


def ensure_columns(apps, schema_editor):
    LessonPlan = apps.get_model('lesson_plan', 'LessonPlan')
    with connection.cursor() as cursor:
        existing = {col.name for col in connection.introspection.get_table_description(cursor, LessonPlan._meta.db_table)}

    to_add = []
    if 'approved_at' not in existing:
        f = models.DateTimeField(blank=True, null=True, verbose_name='Approved At')
        f.set_attributes_from_name('approved_at')
        to_add.append(('approved_at', f))
    if 'approved_by_id' not in existing:
        f = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, related_name='approved_lesson_plans')
        f.set_attributes_from_name('approved_by')
        to_add.append(('approved_by', f))
    if 'attachments' not in existing:
        f = models.FileField(upload_to='lesson_plans/', blank=True, null=True, verbose_name='Attachments')
        f.set_attributes_from_name('attachments')
        to_add.append(('attachments', f))

    if to_add:
        with connection.schema_editor() as se:
            for name, field in to_add:
                se.add_field(LessonPlan, field)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson_plan', '0003_fix_missing_school_column'),
    ]

    operations = [
        migrations.RunPython(ensure_columns, reverse_code=migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='lessonplan',
                    name='approved_at',
                    field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
                ),
                migrations.AddField(
                    model_name='lessonplan',
                    name='approved_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lesson_plans', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='lessonplan',
                    name='attachments',
                    field=models.FileField(blank=True, null=True, upload_to='lesson_plans/', verbose_name='Attachments'),
                ),
            ],
        ),
    ]
