# Generated by Django 4.2.7 on 2026-01-20 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson_plan', '0003_fix_missing_school_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lesson_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='lesson_plans/', verbose_name='Attachments'),
        ),
    ]
