# Generated by Django 4.2.7 on 2026-01-12 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_school_institution_type'),
        ('leave_management', '0002_leave_staff_alter_leave_applicant_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.school'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.school'),
        ),
    ]
