# Generated by Django 6.1.1 on 2026-09-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_leave_school_leavetype_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_sample_data',
            field=models.BooleanField(default=False, verbose_name='Is Sample Data'),
        ),
    ]
