# Generated by Django 4.2.7 on 2025-11-13 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('academics', '0004_class_school_subject_school'),
        ('students', '0001_initial'),
        ('core', '0002_add_admission_number_prefix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='Certificate Number')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('certificate_data', models.JSONField(blank=True, default=dict, help_text='JSON data used to render the certificate template', verbose_name='Certificate Data')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/issued/', verbose_name='Certificate File')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='certificates/qrcodes/', verbose_name='QR Code')),
                ('verification_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Verification Code')),
                ('is_verified', models.BooleanField(default=True, verbose_name='Is Verified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='Is Revoked')),
                ('revocation_reason', models.TextField(blank=True, verbose_name='Revocation Reason')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='core.academicyear')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='IDCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('front_background', models.ImageField(blank=True, null=True, upload_to='id_cards/templates/', verbose_name='Front Background')),
                ('back_background', models.ImageField(blank=True, null=True, upload_to='id_cards/templates/', verbose_name='Back Background')),
                ('width_mm', models.PositiveIntegerField(default=86, verbose_name='Width (mm)')),
                ('height_mm', models.PositiveIntegerField(default=54, verbose_name='Height (mm)')),
                ('front_layout', models.JSONField(blank=True, default=dict, help_text='JSON configuration for front layout elements', verbose_name='Front Layout')),
                ('back_layout', models.JSONField(blank=True, default=dict, help_text='JSON configuration for back layout elements', verbose_name='Back Layout')),
                ('school_logo_position', models.CharField(blank=True, default='top-left', max_length=20, verbose_name='School Logo Position')),
                ('photo_position', models.CharField(blank=True, default='top-right', max_length=20, verbose_name='Photo Position')),
                ('signature_position', models.CharField(blank=True, default='bottom-right', max_length=20, verbose_name='Signature Position')),
                ('primary_color', models.CharField(default='#003366', max_length=10, verbose_name='Primary Color')),
                ('secondary_color', models.CharField(default='#ffffff', max_length=10, verbose_name='Secondary Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_card_templates', to='tenants.school')),
            ],
            options={
                'verbose_name': 'ID Card Template',
                'verbose_name_plural': 'ID Card Templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True, verbose_name='Card Number')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('valid_from', models.DateField(verbose_name='Valid From')),
                ('valid_until', models.DateField(verbose_name='Valid Until')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='Barcode')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='id_cards/qrcodes/', verbose_name='QR Code')),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='id_cards/issued/', verbose_name='Front Image')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='id_cards/issued/', verbose_name='Back Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_lost', models.BooleanField(default=False, verbose_name='Is Lost')),
                ('lost_date', models.DateField(blank=True, null=True, verbose_name='Lost Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_cards', to='core.academicyear')),
                ('card_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='certificates.idcardtemplate')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_id_cards', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='students.student')),
            ],
            options={
                'verbose_name': 'ID Card',
                'verbose_name_plural': 'ID Cards',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='CertificateVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=50, verbose_name='Verification Code')),
                ('verification_date', models.DateTimeField(auto_now_add=True, verbose_name='Verification Date')),
                ('verified_by_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Verified By IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Is Valid')),
                ('verification_message', models.CharField(blank=True, max_length=255, verbose_name='Verification Message')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='certificates.certificate')),
            ],
            options={
                'verbose_name': 'Certificate Verification',
                'verbose_name_plural': 'Certificate Verifications',
                'ordering': ['-verification_date'],
            },
        ),
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Certificate Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Certificate Code')),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('achievement', 'Achievement'), ('participation', 'Participation'), ('completion', 'Completion'), ('attendance', 'Attendance'), ('other', 'Other')], default='academic', max_length=20, verbose_name='Category')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('template_html', models.TextField(blank=True, help_text='HTML template with placeholders for certificate data. Use {{variable}} syntax.', verbose_name='Template HTML')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificates/templates/', verbose_name='Background Image')),
                ('include_qr_code', models.BooleanField(default=True, verbose_name='Include QR Code')),
                ('enable_verification', models.BooleanField(default=True, verbose_name='Enable Online Verification')),
                ('default_width_mm', models.PositiveIntegerField(default=210, verbose_name='Default Width (mm)')),
                ('default_height_mm', models.PositiveIntegerField(default=297, verbose_name='Default Height (mm)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_types', to='tenants.school')),
            ],
            options={
                'verbose_name': 'Certificate Type',
                'verbose_name_plural': 'Certificate Types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='certificates.certificatetype'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='academics.class'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.student'),
        ),
    ]
