# Generated by Django 6.1.1 on 2026-09-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='navigation_layout',
            field=models.CharField(blank=True, choices=[('', 'Use School Default'), ('sidebar', 'Vertical Sidebar'), ('horizontal', 'Horizontal Tabs')], default='', max_length=20, verbose_name='Navigation Layout Preference'),
        ),
    ]
