# Generated by Django 6.1.1 on 2026-10-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_sample_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email and Password'), ('google', 'Google Sign-In')], default='email', help_text='Method used to authenticate/register (Email & Password or Google Sign-In)', max_length=20, verbose_name='Authentication Method'),
        ),
    ]
