# Generated by Django 4.2.7 on 2025-12-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('bank', 'Bank Transfer')], max_length=50, unique=True, verbose_name='Payment Gateway')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=10, verbose_name='Environment')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('mpesa_consumer_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='M-Pesa Consumer Key')),
                ('mpesa_consumer_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='M-Pesa Consumer Secret')),
                ('mpesa_passkey', models.CharField(blank=True, max_length=255, null=True, verbose_name='M-Pesa Passkey')),
                ('mpesa_shortcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='M-Pesa Shortcode')),
                ('mpesa_paybill_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='M-Pesa Paybill Number')),
                ('paypal_client_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='PayPal Client ID')),
                ('paypal_client_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='PayPal Client Secret')),
                ('paypal_webhook_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='PayPal Webhook ID')),
                ('stripe_publishable_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Publishable Key')),
                ('stripe_secret_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Secret Key')),
                ('stripe_webhook_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Webhook Secret')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Name')),
                ('bank_account_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Account Name')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Account Number')),
                ('bank_branch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Branch')),
                ('bank_swift_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Bank SWIFT Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Payment Configuration',
                'verbose_name_plural': 'Payment Configurations',
            },
        ),
    ]
