# Generated by Django 4.2.7 on 2025-12-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_add_mpessa_stk_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolpaymentconfiguration',
            name='mpesa_paybill_account_number',
            field=models.CharField(blank=True, help_text='Account number for M-Pesa paybill payments (visible to parents)', max_length=20, null=True, verbose_name='M-Pesa Paybill Account Number'),
        ),
        migrations.AlterField(
            model_name='schoolpaymentconfiguration',
            name='mpesa_paybill_bank_name',
            field=models.CharField(blank=True, help_text='Bank name associated with M-Pesa paybill (visible to parents)', max_length=255, null=True, verbose_name='M-Pesa Paybill Bank Name'),
        ),
        migrations.AlterField(
            model_name='schoolpaymentconfiguration',
            name='mpesa_paybill_number',
            field=models.CharField(blank=True, help_text='Your M-Pesa paybill number for manual payments', max_length=10, null=True, verbose_name='M-Pesa Paybill Number'),
        ),
        migrations.AlterField(
            model_name='schoolpaymentconfiguration',
            name='mpesa_shortcode',
            field=models.CharField(blank=True, help_text='Your M-Pesa business shortcode for STK Push', max_length=10, null=True, verbose_name='M-Pesa Shortcode'),
        ),
    ]
