# Generated by Django 4.2.7 on 2026-01-05 07:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_school_institution_type'),
        ('superadmin', '0006_globaldatabaseconfiguration_globalemailconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('local', 'Local Model')], default='openai', max_length=50, verbose_name='AI Provider')),
                ('is_active', models.BooleanField(default=False, help_text='Enable AI features across all schools', verbose_name='Is Active')),
                ('openai_api_key', models.CharField(blank=True, help_text='Your OpenAI API key', max_length=255, null=True, verbose_name='OpenAI API Key')),
                ('openai_model', models.CharField(blank=True, default='gpt-4', help_text='Default model to use for OpenAI (e.g., gpt-4, gpt-3.5-turbo)', max_length=100, null=True, verbose_name='OpenAI Model')),
                ('azure_openai_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Azure OpenAI API Key')),
                ('azure_openai_endpoint', models.URLField(blank=True, null=True, verbose_name='Azure OpenAI Endpoint')),
                ('azure_openai_deployment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Azure OpenAI Deployment')),
                ('anthropic_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Anthropic API Key')),
                ('anthropic_model', models.CharField(blank=True, default='claude-2', max_length=100, null=True, verbose_name='Anthropic Model')),
                ('local_model_path', models.CharField(blank=True, help_text='Path to the local model files', max_length=500, null=True, verbose_name='Local Model Path')),
                ('temperature', models.FloatField(default=0.7, help_text='Controls randomness in the AI responses (0.0 to 2.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Temperature')),
                ('max_tokens', models.PositiveIntegerField(default=1000, help_text='Maximum number of tokens to generate in the response', verbose_name='Max Tokens')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Global AI Configuration',
                'verbose_name_plural': 'Global AI Configurations',
            },
        ),
        migrations.CreateModel(
            name='SchoolAIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Enable AI features for this school', verbose_name='Is Active')),
                ('use_global_settings', models.BooleanField(default=True, help_text='Use global AI configuration settings', verbose_name='Use Global Settings')),
                ('provider', models.CharField(blank=True, choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('local', 'Local Model')], default='openai', help_text='Override global AI provider settings', max_length=50, null=True, verbose_name='AI Provider Override')),
                ('openai_api_key', models.CharField(blank=True, help_text='Override global OpenAI API key', max_length=255, null=True, verbose_name='OpenAI API Key (Override)')),
                ('openai_model', models.CharField(blank=True, help_text='Override global OpenAI model', max_length=100, null=True, verbose_name='OpenAI Model (Override)')),
                ('azure_openai_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Azure OpenAI API Key (Override)')),
                ('azure_openai_endpoint', models.URLField(blank=True, null=True, verbose_name='Azure OpenAI Endpoint (Override)')),
                ('azure_openai_deployment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Azure OpenAI Deployment (Override)')),
                ('anthropic_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Anthropic API Key (Override)')),
                ('anthropic_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Anthropic Model (Override)')),
                ('local_model_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Local Model Path (Override)')),
                ('temperature', models.FloatField(blank=True, help_text='Override global temperature setting', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Temperature (Override)')),
                ('max_tokens', models.PositiveIntegerField(blank=True, help_text='Override global max tokens setting', null=True, verbose_name='Max Tokens (Override)')),
                ('include_student_data', models.BooleanField(default=True, help_text='Allow AI to access student data for context', verbose_name='Include Student Data')),
                ('include_academic_data', models.BooleanField(default=True, help_text='Allow AI to access academic records for context', verbose_name='Include Academic Data')),
                ('include_financial_data', models.BooleanField(default=False, help_text='Allow AI to access financial data for context', verbose_name='Include Financial Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_configurations', to='tenants.school', verbose_name='School')),
            ],
            options={
                'verbose_name': 'School AI Configuration',
                'verbose_name_plural': 'School AI Configurations',
                'unique_together': {('school',)},
            },
        ),
    ]
