# Generated by Django 4.2.7 on 2026-01-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_globalaiconfiguration_schoolaiconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalaiconfiguration',
            name='google_api_key',
            field=models.CharField(blank=True, help_text='Your Google AI Studio API key', max_length=255, null=True, verbose_name='Google API Key'),
        ),
        migrations.AddField(
            model_name='globalaiconfiguration',
            name='google_model',
            field=models.CharField(blank=True, default='gemini-1.5-flash', help_text='Default model to use for Google Gemini (e.g., gemini-1.5-flash, gemini-1.5-pro)', max_length=100, null=True, verbose_name='Google Model'),
        ),
        migrations.AddField(
            model_name='schoolaiconfiguration',
            name='google_api_key',
            field=models.CharField(blank=True, help_text='Override global Google API key', max_length=255, null=True, verbose_name='Google API Key (Override)'),
        ),
        migrations.AddField(
            model_name='schoolaiconfiguration',
            name='google_model',
            field=models.CharField(blank=True, help_text='Override global Google model', max_length=100, null=True, verbose_name='Google Model (Override)'),
        ),
        migrations.AlterField(
            model_name='globalaiconfiguration',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google Gemini'), ('local', 'Local Model')], default='openai', max_length=50, verbose_name='AI Provider'),
        ),
        migrations.AlterField(
            model_name='schoolaiconfiguration',
            name='provider',
            field=models.CharField(blank=True, choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google Gemini'), ('local', 'Local Model')], default='openai', help_text='Override global AI provider settings', max_length=50, null=True, verbose_name='AI Provider Override'),
        ),
    ]
