# Generated by Django 4.2.7 on 2026-01-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_add_google_gemini_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolpaymentconfiguration',
            name='mpesa_pochi_number',
            field=models.CharField(blank=True, help_text='Pochi account phone number for receiving payments', max_length=20, null=True, verbose_name='Pochi la Biashara Number'),
        ),
        migrations.AddField(
            model_name='schoolpaymentconfiguration',
            name='mpesa_send_money_recipient',
            field=models.CharField(blank=True, help_text='Phone number to receive M-Pesa Send Money payments', max_length=20, null=True, verbose_name='M-Pesa Send Money Recipient'),
        ),
        migrations.AddField(
            model_name='schoolpaymentconfiguration',
            name='mpesa_till_number',
            field=models.CharField(blank=True, help_text='Your M-Pesa till number for Buy Goods & Services payments', max_length=10, null=True, verbose_name='M-Pesa Till Number'),
        ),
        migrations.AlterField(
            model_name='schoolpaymentconfiguration',
            name='gateway',
            field=models.CharField(choices=[('mpesa_stk', 'M-Pesa STK Push'), ('mpesa_paybill', 'M-Pesa Manual Paybill'), ('mpesa_buygoods', 'Lipa na M-Pesa (Buy Goods & Services)'), ('mpesa_send_money', 'M-Pesa Send Money'), ('mpesa_pochi', 'M-Pesa Pochi la Biashara'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=50, verbose_name='Payment Gateway'),
        ),
    ]
