# Generated by Django 4.2.7 on 2026-01-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_schoolpaymentconfiguration_mpesa_pochi_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolpaymentconfiguration',
            name='mpesa_buygoods_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='M-Pesa Buy Goods Instructions'),
        ),
        migrations.AddField(
            model_name='schoolpaymentconfiguration',
            name='mpesa_paybill_account_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='M-Pesa Paybill Account Name'),
        ),
        migrations.AddField(
            model_name='schoolpaymentconfiguration',
            name='mpesa_paybill_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='M-Pesa Paybill Instructions'),
        ),
        migrations.AddField(
            model_name='schoolpaymentconfiguration',
            name='mpesa_pochi_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='M-Pesa Pochi Instructions'),
        ),
        migrations.AddField(
            model_name='schoolpaymentconfiguration',
            name='mpesa_send_money_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='M-Pesa Send Money Instructions'),
        ),
        migrations.AlterField(
            model_name='paymentconfiguration',
            name='gateway',
            field=models.CharField(choices=[('mpesa_stk', 'M-Pesa STK Push'), ('mpesa_paybill', 'M-Pesa Manual Paybill'), ('mpesa_buygoods', 'Lipa na M-Pesa (Buy Goods & Services)'), ('mpesa_send_money', 'M-Pesa Send Money'), ('mpesa_pochi', 'M-Pesa Pochi la Biashara'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=50, unique=True, verbose_name='Payment Gateway'),
        ),
    ]
