# Generated by Django 4.2.7 on 2026-01-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_schoolpaymentconfiguration_mpesa_buygoods_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfiguration',
            name='mpesa_buygoods_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='M-Pesa Buy Goods Instructions'),
        ),
        migrations.AddField(
            model_name='paymentconfiguration',
            name='mpesa_paybill_account_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='M-Pesa Paybill Account Name'),
        ),
        migrations.AddField(
            model_name='paymentconfiguration',
            name='mpesa_paybill_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='M-Pesa Paybill Instructions'),
        ),
        migrations.AddField(
            model_name='paymentconfiguration',
            name='mpesa_pochi_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='M-Pesa Pochi Instructions'),
        ),
        migrations.AddField(
            model_name='paymentconfiguration',
            name='mpesa_pochi_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pochi la Biashara Number'),
        ),
        migrations.AddField(
            model_name='paymentconfiguration',
            name='mpesa_send_money_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='M-Pesa Send Money Instructions'),
        ),
        migrations.AddField(
            model_name='paymentconfiguration',
            name='mpesa_send_money_recipient',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='M-Pesa Send Money Recipient'),
        ),
        migrations.AddField(
            model_name='paymentconfiguration',
            name='mpesa_till_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='M-Pesa Till Number'),
        ),
    ]
