# Generated by Django 6.1.1 on 2026-09-14 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0011_paymentconfiguration_mpesa_buygoods_instructions_and_more'),
        ('tenants', '0002_school_institution_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_alias', models.CharField(default='default', max_length=100, verbose_name='Database Alias')),
                ('backup_type', models.CharField(choices=[('master', 'Master Database'), ('tenant', 'Tenant Database')], default='tenant', max_length=20, verbose_name='Backup Type')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('file_path', models.CharField(max_length=500, verbose_name='File Path')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='File Size (Bytes)')),
                ('engine', models.CharField(default='sqlite3', max_length=50, verbose_name='Database Engine')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('in_progress', 'In Progress')], default='completed', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_database_backups', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('school', models.ForeignKey(blank=True, help_text='Associated school tenant. Null indicates the master database.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='database_backups', to='tenants.school')),
            ],
            options={
                'verbose_name': 'Database Backup',
                'verbose_name_plural': 'Database Backups',
                'ordering': ['-created_at'],
            },
        ),
    ]
