# Generated by Django 6.1.1 on 2026-09-15 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0012_databasebackup'),
        ('tenants', '0002_school_institution_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalWhatsAppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('meta', 'Meta WhatsApp Cloud API'), ('twilio', 'Twilio WhatsApp'), ('africastalking', "Africa's Talking WhatsApp"), ('infobip', 'Infobip WhatsApp')], max_length=20, unique=True, verbose_name='WhatsApp Provider')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('meta_phone_number_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta Phone Number ID')),
                ('meta_waba_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='WhatsApp Business Account ID (WABA)')),
                ('meta_access_token', models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta Access Token')),
                ('meta_app_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta App ID')),
                ('meta_app_secret', models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta App Secret')),
                ('meta_webhook_verify_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Webhook Verify Token')),
                ('twilio_account_sid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twilio Account SID')),
                ('twilio_auth_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twilio Auth Token')),
                ('twilio_from_number', models.CharField(blank=True, help_text='Format: whatsapp:+14155238886', max_length=50, null=True, verbose_name='Twilio From WhatsApp Number')),
                ('africastalking_username', models.CharField(blank=True, max_length=255, null=True, verbose_name="Africa's Talking Username")),
                ('africastalking_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name="Africa's Talking API Key")),
                ('africastalking_sender_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name="Africa's Talking Sender Phone")),
                ('infobip_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Infobip API Key')),
                ('infobip_base_url', models.URLField(blank=True, default='https://api.infobip.com', null=True, verbose_name='Infobip Base URL')),
                ('infobip_sender_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Infobip Sender Phone Number')),
                ('default_sender_phone', models.CharField(blank=True, help_text='Default outgoing phone number for WhatsApp notifications', max_length=50, null=True, verbose_name='Default Sender Phone Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Global WhatsApp Configuration',
                'verbose_name_plural': 'Global WhatsApp Configurations',
            },
        ),
        migrations.CreateModel(
            name='SchoolWhatsAppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('meta', 'Meta WhatsApp Cloud API'), ('twilio', 'Twilio WhatsApp'), ('africastalking', "Africa's Talking WhatsApp"), ('infobip', 'Infobip WhatsApp')], max_length=20, verbose_name='WhatsApp Provider')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('use_global_settings', models.BooleanField(default=True, help_text='Use global WhatsApp configuration settings', verbose_name='Use Global Settings')),
                ('meta_phone_number_id', models.CharField(blank=True, help_text='Override global Meta Phone Number ID', max_length=100, null=True, verbose_name='Meta Phone Number ID')),
                ('meta_waba_id', models.CharField(blank=True, help_text='Override global WABA ID', max_length=100, null=True, verbose_name='WhatsApp Business Account ID (WABA)')),
                ('meta_access_token', models.CharField(blank=True, help_text='Override global Meta Access Token', max_length=500, null=True, verbose_name='Meta Access Token')),
                ('meta_app_id', models.CharField(blank=True, help_text='Override global Meta App ID', max_length=100, null=True, verbose_name='Meta App ID')),
                ('meta_app_secret', models.CharField(blank=True, help_text='Override global Meta App Secret', max_length=100, null=True, verbose_name='Meta App Secret')),
                ('meta_webhook_verify_token', models.CharField(blank=True, help_text='Override global Webhook Verify Token', max_length=100, null=True, verbose_name='Webhook Verify Token')),
                ('twilio_account_sid', models.CharField(blank=True, help_text='Override global Twilio Account SID', max_length=255, null=True, verbose_name='Twilio Account SID')),
                ('twilio_auth_token', models.CharField(blank=True, help_text='Override global Twilio Auth Token', max_length=255, null=True, verbose_name='Twilio Auth Token')),
                ('twilio_from_number', models.CharField(blank=True, help_text='Format: whatsapp:+14155238886', max_length=50, null=True, verbose_name='Twilio From WhatsApp Number')),
                ('africastalking_username', models.CharField(blank=True, help_text="Override global Africa's Talking Username", max_length=255, null=True, verbose_name="Africa's Talking Username")),
                ('africastalking_api_key', models.CharField(blank=True, help_text="Override global Africa's Talking API Key", max_length=255, null=True, verbose_name="Africa's Talking API Key")),
                ('africastalking_sender_phone', models.CharField(blank=True, help_text="Override global Africa's Talking Sender Phone", max_length=50, null=True, verbose_name="Africa's Talking Sender Phone")),
                ('infobip_api_key', models.CharField(blank=True, help_text='Override global Infobip API Key', max_length=255, null=True, verbose_name='Infobip API Key')),
                ('infobip_base_url', models.URLField(blank=True, default='https://api.infobip.com', null=True, verbose_name='Infobip Base URL')),
                ('infobip_sender_phone', models.CharField(blank=True, help_text='Override global Infobip Sender Phone Number', max_length=50, null=True, verbose_name='Infobip Sender Phone Number')),
                ('custom_sender_phone', models.CharField(blank=True, help_text='School-specific sender phone for WhatsApp messages', max_length=50, null=True, verbose_name='Custom Sender Phone')),
                ('daily_whatsapp_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of WhatsApp messages per day (0 = unlimited)', null=True, verbose_name='Daily WhatsApp Limit')),
                ('monthly_whatsapp_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of WhatsApp messages per month (0 = unlimited)', null=True, verbose_name='Monthly WhatsApp Limit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_configurations', to='tenants.school', verbose_name='School')),
            ],
            options={
                'verbose_name': 'School WhatsApp Configuration',
                'verbose_name_plural': 'School WhatsApp Configurations',
                'unique_together': {('school', 'provider')},
            },
        ),
    ]
