# Generated by Django 6.1.1 on 2026-09-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_globalwhatsappconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsmsconfiguration',
            name='mobilesasa_api_token',
            field=models.CharField(blank=True, help_text='Bearer token from MobileSasa dashboard (e.g. mbs_...)', max_length=255, null=True, verbose_name='MobileSasa API Token'),
        ),
        migrations.AddField(
            model_name='globalsmsconfiguration',
            name='mobilesasa_sender_id',
            field=models.CharField(blank=True, help_text='Approved Sender ID from MobileSasa', max_length=50, null=True, verbose_name='MobileSasa Sender ID'),
        ),
        migrations.AddField(
            model_name='globalwhatsappconfiguration',
            name='mobilesasa_account_uuid',
            field=models.CharField(blank=True, help_text='UUID of the connected WhatsApp account in MobileSasa', max_length=100, null=True, verbose_name='MobileSasa WhatsApp Account UUID'),
        ),
        migrations.AddField(
            model_name='globalwhatsappconfiguration',
            name='mobilesasa_api_token',
            field=models.CharField(blank=True, help_text='Bearer token from MobileSasa dashboard (e.g. mbs_...)', max_length=255, null=True, verbose_name='MobileSasa API Token'),
        ),
        migrations.AddField(
            model_name='globalwhatsappconfiguration',
            name='mobilesasa_sender_phone',
            field=models.CharField(blank=True, help_text='Phone number registered on WhatsApp account', max_length=50, null=True, verbose_name='MobileSasa Sender Phone Number'),
        ),
        migrations.AddField(
            model_name='schoolsmsconfiguration',
            name='mobilesasa_api_token',
            field=models.CharField(blank=True, help_text='Override global MobileSasa API Token', max_length=255, null=True, verbose_name='MobileSasa API Token'),
        ),
        migrations.AddField(
            model_name='schoolsmsconfiguration',
            name='mobilesasa_sender_id',
            field=models.CharField(blank=True, help_text='Override global MobileSasa Sender ID', max_length=50, null=True, verbose_name='MobileSasa Sender ID'),
        ),
        migrations.AddField(
            model_name='schoolwhatsappconfiguration',
            name='mobilesasa_account_uuid',
            field=models.CharField(blank=True, help_text='Override global MobileSasa WhatsApp Account UUID', max_length=100, null=True, verbose_name='MobileSasa WhatsApp Account UUID'),
        ),
        migrations.AddField(
            model_name='schoolwhatsappconfiguration',
            name='mobilesasa_api_token',
            field=models.CharField(blank=True, help_text='Override global MobileSasa API Token', max_length=255, null=True, verbose_name='MobileSasa API Token'),
        ),
        migrations.AddField(
            model_name='schoolwhatsappconfiguration',
            name='mobilesasa_sender_phone',
            field=models.CharField(blank=True, help_text='Override global MobileSasa Sender Phone Number', max_length=50, null=True, verbose_name='MobileSasa Sender Phone Number'),
        ),
        migrations.AlterField(
            model_name='globalsmsconfiguration',
            name='provider',
            field=models.CharField(choices=[('mobilesasa', 'MobileSasa'), ('twilio', 'Twilio'), ('africastalking', "Africa's Talking"), ('infobip', 'Infobip'), ('clickatell', 'Clickatell'), ('nexmo', 'Nexmo (Vonage)')], max_length=20, unique=True, verbose_name='SMS Provider'),
        ),
        migrations.AlterField(
            model_name='globalwhatsappconfiguration',
            name='provider',
            field=models.CharField(choices=[('mobilesasa', 'MobileSasa WhatsApp'), ('meta', 'Meta WhatsApp Cloud API'), ('twilio', 'Twilio WhatsApp'), ('africastalking', "Africa's Talking WhatsApp"), ('infobip', 'Infobip WhatsApp')], max_length=20, unique=True, verbose_name='WhatsApp Provider'),
        ),
        migrations.AlterField(
            model_name='schoolsmsconfiguration',
            name='provider',
            field=models.CharField(choices=[('mobilesasa', 'MobileSasa'), ('twilio', 'Twilio'), ('africastalking', "Africa's Talking"), ('infobip', 'Infobip'), ('clickatell', 'Clickatell'), ('nexmo', 'Nexmo (Vonage)')], max_length=20, verbose_name='SMS Provider'),
        ),
        migrations.AlterField(
            model_name='schoolwhatsappconfiguration',
            name='provider',
            field=models.CharField(choices=[('mobilesasa', 'MobileSasa WhatsApp'), ('meta', 'Meta WhatsApp Cloud API'), ('twilio', 'Twilio WhatsApp'), ('africastalking', "Africa's Talking WhatsApp"), ('infobip', 'Infobip WhatsApp')], max_length=20, verbose_name='WhatsApp Provider'),
        ),
    ]
