# Generated by Django 6.1.1 on 2026-10-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0014_globalsmsconfiguration_mobilesasa_api_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalGoogleAuthConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, help_text='OAuth 2.0 Client ID from Google Cloud Console (e.g. xxxxxxxx.apps.googleusercontent.com)', max_length=255, null=True, verbose_name='Google Client ID')),
                ('client_secret', models.CharField(blank=True, help_text='OAuth 2.0 Client Secret from Google Cloud Console (e.g. GOCSPX-xxxxxxxx)', max_length=255, null=True, verbose_name='Google Client Secret')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable Google Sign-In on login and register modals', verbose_name='Enable Google Sign-In')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Global Google Auth Configuration',
                'verbose_name_plural': 'Global Google Auth Configurations',
            },
        ),
    ]
