# Generated by Django 6.1.1 on 2026-10-03 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0015_globalgoogleauthconfiguration'),
        ('tenants', '0002_school_institution_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique identifier code, e.g. fee_reminder, payment_receipt, welcome_user', max_length=100, verbose_name='Template Code')),
                ('name', models.CharField(help_text='Descriptive name, e.g. Fee Balance Reminder', max_length=255, verbose_name='Template Name')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=20, verbose_name='Channel')),
                ('category', models.CharField(choices=[('fees', 'Fees & Finance'), ('academics', 'Academics & Exams'), ('attendance', 'Attendance'), ('notices', 'Notices & Announcements'), ('system', 'System & Account'), ('other', 'Other')], default='other', max_length=30, verbose_name='Category')),
                ('subject', models.CharField(blank=True, help_text='Email subject line. Supports dynamic tags like {{ student_name }}', max_length=255, verbose_name='Subject')),
                ('heading', models.CharField(blank=True, help_text='Main title displayed inside email body above content', max_length=255, verbose_name='Headline / Title')),
                ('body', models.TextField(help_text='Body text with dynamic tags (e.g., {{ student_name }}, {{ balance }})', verbose_name='Message Body / Content')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='templates/banners/', verbose_name='Hero / Feature Banner Image')),
                ('button_text', models.CharField(blank=True, help_text='e.g. READ MORE HERE, PAY NOW, VIEW INVOICE', max_length=100, verbose_name='Action Button Text')),
                ('button_url', models.CharField(blank=True, help_text='Target URL or dynamic tag e.g. {{ payment_url }}', max_length=500, verbose_name='Action Button URL')),
                ('available_tags', models.CharField(blank=True, help_text='Comma-separated list of tags, e.g. student_name, balance, due_date, school_name', max_length=500, verbose_name='Available Tags')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_system', models.BooleanField(default=False, verbose_name='Built-in System Template')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('school', models.ForeignKey(blank=True, help_text='If empty, this is a global system template', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='tenants.school', verbose_name='School')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['channel', 'category', 'name'],
                'constraints': [models.UniqueConstraint(fields=('school', 'code', 'channel'), name='unique_school_channel_code')],
            },
        ),
    ]
