# Generated by Django 4.2.7 on 2025-11-13 13:22

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0004_class_school_subject_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', ckeditor.fields.RichTextField(verbose_name='Question')),
                ('question_type', models.CharField(choices=[('mcq_single', 'Multiple Choice (Single Answer)'), ('mcq_multiple', 'Multiple Choice (Multiple Answers)'), ('true_false', 'True or False'), ('short_answer', 'Short Answer'), ('essay', 'Essay/Long Answer'), ('matching', 'Matching'), ('fill_blank', 'Fill in the Blank')], max_length=15, verbose_name='Question Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exam_questions/', verbose_name='Question Image')),
                ('marks', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Marks')),
                ('is_required', models.BooleanField(default=True, verbose_name='Is Required')),
                ('explanation', models.TextField(blank=True, help_text='Explanation of the correct answer', verbose_name='Explanation')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Question',
                'verbose_name_plural': 'Exam Questions',
                'ordering': ['exam', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=500, verbose_name='Choice Text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='online_exam.examquestion')),
            ],
            options={
                'verbose_name': 'Question Choice',
                'verbose_name_plural': 'Question Choices',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='OnlineExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Exam Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('instructions', ckeditor.fields.RichTextField(blank=True, verbose_name='Exam Instructions')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Duration (minutes)')),
                ('passing_percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Passing Percentage')),
                ('total_marks', models.PositiveIntegerField(default=0, verbose_name='Total Marks')),
                ('negative_marking', models.BooleanField(default=False, verbose_name='Negative Marking')),
                ('negative_mark_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Marks Deducted per Wrong Answer')),
                ('is_randomized', models.BooleanField(default=True, verbose_name='Randomize Questions')),
                ('allow_attempt_review', models.BooleanField(default=True, verbose_name='Allow Attempt Review')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('mixed', 'Mixed')], default='medium', max_length=10, verbose_name='Difficulty Level')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=15, verbose_name='Status')),
                ('publish_results', models.BooleanField(default=False, verbose_name='Publish Results')),
                ('show_answer_key', models.BooleanField(default=False, verbose_name='Show Answer Key After Exam')),
                ('require_webcam', models.BooleanField(default=False, verbose_name='Require Webcam')),
                ('prevent_tab_switching', models.BooleanField(default=True, verbose_name='Prevent Tab Switching')),
                ('max_attempts', models.PositiveSmallIntegerField(default=1, verbose_name='Maximum Attempts Allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_exams', to='academics.class', verbose_name='Class')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_exams', to='tenants.school')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_exams', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_exams', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Online Exam',
                'verbose_name_plural': 'Online Exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='online_exam.onlineexam'),
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('auto_submitted', 'Auto Submitted'), ('graded', 'Graded')], default='not_started', max_length=15, verbose_name='Status')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Score')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentage')),
                ('passed', models.BooleanField(default=False, verbose_name='Passed')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, verbose_name='Attempt Number')),
                ('questions_answered', models.PositiveIntegerField(default=0, verbose_name='Questions Answered')),
                ('questions_correct', models.PositiveIntegerField(default=0, verbose_name='Questions Correct')),
                ('time_taken_seconds', models.PositiveIntegerField(default=0, verbose_name='Time Taken (seconds)')),
                ('browser_fingerprint', models.CharField(blank=True, max_length=255, verbose_name='Browser Fingerprint')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('tab_switches', models.PositiveSmallIntegerField(default=0, verbose_name='Tab/Window Switches')),
                ('integrity_flags', models.PositiveSmallIntegerField(default=0, verbose_name='Integrity Flags')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='online_exam.onlineexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='students.student')),
            ],
            options={
                'verbose_name': 'Exam Attempt',
                'verbose_name_plural': 'Exam Attempts',
                'ordering': ['-submitted_at', '-created_at'],
                'unique_together': {('exam', 'student', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='Text Answer')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Is Correct')),
                ('marks_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Marks Awarded')),
                ('answer_time', models.DateTimeField(auto_now_add=True, verbose_name='Answer Time')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='online_exam.examattempt')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='online_exam.examquestion')),
                ('selected_choices', models.ManyToManyField(related_name='selected_by', to='online_exam.questionchoice')),
            ],
            options={
                'verbose_name': 'Student Answer',
                'verbose_name_plural': 'Student Answers',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
