# Generated by Django 4.2.7 on 2026-01-19 08:12

from django.db import migrations, models


def dedupe_staff_payments(apps, schema_editor):
    StaffPayment = apps.get_model('inventory', 'StaffPayment')
    Expense = apps.get_model('inventory', 'Expense')

    # Build groups keyed by (school_id, staff_type, staff_id, payment_month)
    groups = {}
    for sp in StaffPayment.objects.all().only(
        'id', 'school_id', 'staff_type', 'staff_id', 'payment_month', 'status', 'payment_date', 'created_at', 'expense_id'
    ):
        key = (sp.school_id, sp.staff_type, sp.staff_id, sp.payment_month)
        groups.setdefault(key, []).append(sp)

    # For any group with >1, keep the best candidate and remove the rest
    for key, items in groups.items():
        if len(items) <= 1:
            continue

        # Preference: 'paid' over others, then latest payment_date, then highest id
        def sort_key(x):
            from datetime import date
            paid_rank = 0 if (str(getattr(x, 'status', '')).lower() == 'paid') else 1
            pd = getattr(x, 'payment_date', None)
            # Use toordinal for ordering dates; negate to have latest first
            pd_ord = -(pd.toordinal()) if pd else -(date.min.toordinal())
            return (paid_rank, pd_ord, -x.id)

        items_sorted = sorted(items, key=sort_key)
        keep = items_sorted[0]

        for sp in items_sorted[1:]:
            # If duplicate has an attached expense, delete it to avoid double-counting
            if getattr(sp, 'expense_id', None):
                try:
                    Expense.objects.filter(id=sp.expense_id).delete()
                except Exception:
                    pass
            # Delete the duplicate StaffPayment
            try:
                sp.delete()
            except Exception:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_school_scoping'),
    ]

    operations = [
        migrations.RunPython(dedupe_staff_payments, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='staffpayment',
            constraint=models.UniqueConstraint(fields=('school', 'staff_type', 'staff_id', 'payment_month'), name='uniq_staff_payment_per_month_per_person_per_school'),
        ),
    ]
