# Generated by Django 4.2.7 on 2026-02-04 08:43

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0002_school_institution_type'),
        ('inventory', '0003_staffpayment_uniq_staff_payment_per_month_per_person_per_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canteen_categories', to='tenants.school')),
            ],
            options={
                'verbose_name': 'Canteen Category',
                'verbose_name_plural': 'Canteen Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CanteenProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('code', models.CharField(max_length=50, verbose_name='SKU/Code')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('stock_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock Quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.canteencategory')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canteen_products', to='tenants.school')),
            ],
            options={
                'verbose_name': 'Canteen Product',
                'verbose_name_plural': 'Canteen Products',
                'ordering': ['name'],
                'unique_together': {('school', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CanteenSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=50, unique=True, verbose_name='Receipt No')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Discount')),
                ('net_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Net Total')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20, verbose_name='Payment Method')),
                ('amount_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Amount Received')),
                ('change_given', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Change Given')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_canteen_sales', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canteen_sales', to='tenants.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canteen_sales', to='students.student')),
            ],
            options={
                'verbose_name': 'Canteen Sale',
                'verbose_name_plural': 'Canteen Sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CanteenSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qty')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Line Total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.canteenproduct')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.canteensale')),
            ],
            options={
                'verbose_name': 'Canteen Sale Item',
                'verbose_name_plural': 'Canteen Sale Items',
            },
        ),
    ]
