# Generated by Django 4.2.7 on 2026-02-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_canteencategory_canteenproduct_canteensale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='is_canteen',
            field=models.BooleanField(default=False, verbose_name='Canteen (POS) Category'),
        ),
    ]
