# Generated by Django 4.2.7 on 2026-03-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_itemcategory_is_canteen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='category_type',
            field=models.CharField(choices=[('stationery', 'Stationery'), ('food', 'Food & Beverages'), ('equipment', 'Equipment'), ('furniture', 'Furniture'), ('supplies', 'Supplies'), ('canteen', 'Canteen'), ('other', 'Other')], max_length=20, verbose_name='Type'),
        ),
    ]
