# Generated by Django 4.2.7 on 2025-11-13 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Report Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('module', models.CharField(help_text='e.g., academics, attendance, finance', max_length=50, verbose_name='Module')),
                ('icon', models.CharField(default='fa fa-file-alt', max_length=50, verbose_name='Icon Class')),
                ('data_source', models.CharField(help_text='Name of Django model or SQL view', max_length=255, verbose_name='Data Source')),
                ('query_params', models.JSONField(default=dict, help_text='Parameters required for filtering data', verbose_name='Query Parameters')),
                ('date_range_required', models.BooleanField(default=False, verbose_name='Date Range Required')),
                ('columns', models.JSONField(default=list, help_text='Columns to display in the report', verbose_name='Columns')),
                ('chart_types', models.JSONField(default=list, help_text='Available chart types for this report', verbose_name='Chart Types')),
                ('available_to_roles', models.JSONField(default=list, help_text='User roles that can access this report', verbose_name='Available To Roles')),
                ('is_system', models.BooleanField(default=False, help_text='Built-in system report that cannot be deleted', verbose_name='System Report')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_types', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_types', to='tenants.school')),
            ],
            options={
                'verbose_name': 'Report Type',
                'verbose_name_plural': 'Report Types',
                'ordering': ['module', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Report Title')),
                ('parameters', models.JSONField(default=dict, verbose_name='Parameters')),
                ('date_range_start', models.DateField(blank=True, null=True, verbose_name='Date Range Start')),
                ('date_range_end', models.DateField(blank=True, null=True, verbose_name='Date Range End')),
                ('data', models.JSONField(default=dict, verbose_name='Report Data')),
                ('summary', models.JSONField(default=dict, verbose_name='Report Summary')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdf/', verbose_name='PDF Export')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='reports/excel/', verbose_name='Excel Export')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='Is Scheduled')),
                ('schedule_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20, null=True, verbose_name='Schedule Frequency')),
                ('last_generated', models.DateTimeField(blank=True, null=True, verbose_name='Last Generated')),
                ('is_public', models.BooleanField(default=False, help_text='Visible to all users with appropriate permissions', verbose_name='Is Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='reports.reporttype')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='tenants.school')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Report',
                'verbose_name_plural': 'Saved Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Distribution Name')),
                ('email_addresses', models.TextField(blank=True, help_text='Comma-separated list of email addresses', verbose_name='Additional Email Addresses')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20, verbose_name='Frequency')),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='1-7, where 1 is Monday (for weekly)', null=True, verbose_name='Day of Week')),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='1-31 (for monthly)', null=True, verbose_name='Day of Month')),
                ('time_of_day', models.TimeField(verbose_name='Time of Day')),
                ('include_pdf', models.BooleanField(default=True, verbose_name='Include PDF')),
                ('include_excel', models.BooleanField(default=False, verbose_name='Include Excel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='Last Sent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_report_distributions', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(related_name='report_distributions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='reports.savedreport')),
            ],
            options={
                'verbose_name': 'Report Distribution',
                'verbose_name_plural': 'Report Distributions',
            },
        ),
    ]
