# Generated by Django 4.2.7 on 2025-12-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_update_site_domain'),
    ]

    operations = [
    ]
