# Generated by Django 4.2.7 on 2025-12-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_remove_pricingplan_model'),
    ]

    operations = [
    ]
