# Generated by Django 4.2.7 on 2026-02-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_forumthread_forumpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingPlan',
        ),
    ]
