# Generated by Django 6.1.1 on 2026-09-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_delete_pricingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-star', help_text='FontAwesome class e.g. fas fa-user-graduate', max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Item',
                'verbose_name_plural': 'Feature Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_prefix', models.CharField(default='Transform Your', help_text='First part of hero title', max_length=150)),
                ('typing_texts', models.TextField(default='School Management\nAcademic Operations\nLearning Experiences\nCBC & TVET Institutions', help_text='Line-separated phrases for the typing effect')),
                ('subtitle', models.TextField(default='Complete cloud-based solution for modern education management. Streamline operations and enhance learning experiences.')),
                ('primary_btn_text', models.CharField(default='Start Free Trial', max_length=60)),
                ('primary_btn_url', models.CharField(default='#registerModal', help_text='URL or modal target like #registerModal', max_length=255)),
                ('secondary_btn_text', models.CharField(default='Sign In', max_length=60)),
                ('secondary_btn_url', models.CharField(default='#loginModal', help_text='URL or modal target like #loginModal', max_length=255)),
                ('bg_type', models.CharField(choices=[('gradient', 'Modern Dark Gradient'), ('color', 'Solid Color'), ('image', 'Background Image with Overlay')], default='gradient', max_length=20)),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='frontend/hero/')),
                ('bg_color', models.CharField(default='#0f172a', help_text='Hex code or CSS color', max_length=30)),
                ('bg_gradient', models.CharField(default='linear-gradient(135deg, #0f172a 0%, #1e3a5f 50%, #164e63 100%)', help_text='Custom CSS gradient string', max_length=255)),
                ('overlay_opacity', models.FloatField(default=0.85, help_text='Overlay darkness from 0.0 (transparent) to 1.0 (solid)')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section Content',
                'verbose_name_plural': 'Hero Section Content',
            },
        ),
        migrations.CreateModel(
            name='ParallaxSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(blank=True, default='NEXT-GEN EDUCATION', max_length=60)),
                ('title', models.CharField(default='Empowering Kenyan Schools with Cutting-Edge Cloud SaaS', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='Seamless CBC compliance, automated financial ledger, and AI-driven performance tracking.', max_length=255)),
                ('content', models.TextField(blank=True)),
                ('primary_btn_text', models.CharField(blank=True, default='Explore Pricing', max_length=60)),
                ('primary_btn_url', models.CharField(blank=True, default='/pricing/', max_length=255)),
                ('secondary_btn_text', models.CharField(blank=True, default='Get in Touch', max_length=60)),
                ('secondary_btn_url', models.CharField(blank=True, default='/contact/', max_length=255)),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='frontend/parallax/')),
                ('bg_color', models.CharField(default='#0f172a', help_text='Fallback background color', max_length=30)),
                ('overlay_opacity', models.FloatField(default=0.75, help_text='Overlay darkness from 0.0 (transparent) to 1.0 (black/solid)')),
                ('scroll_effect', models.CharField(choices=[('fixed_bg', 'Fixed Background (Classic Parallax)'), ('zoom_in', 'Scroll Zoom In (Expands on Scroll)'), ('zoom_out', 'Scroll Zoom Out (Subtle Shrink)'), ('standard', 'Standard Smooth Translation'), ('none', 'None (Static Background)')], default='fixed_bg', help_text='Parallax movement effect as user scrolls', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parallax Section',
                'verbose_name_plural': 'Parallax Sections',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(default=1, help_text='Order and display number (e.g. 1, 2, 3...)')),
                ('phase_tag', models.CharField(default='PHASE 1', help_text='e.g. PHASE 1, STEP 1', max_length=50)),
                ('title', models.CharField(help_text='e.g. Discovery & Strategy', max_length=150)),
                ('subtitle', models.CharField(blank=True, help_text='Short one-line summary', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of this step')),
                ('icon', models.CharField(default='fas fa-compass', help_text='FontAwesome icon class, e.g. fas fa-cogs', max_length=60)),
                ('accent_color', models.CharField(default='#f59e0b', help_text='Accent color hex code (e.g. #f59e0b, #06b6d4)', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'How It Works Step',
                'verbose_name_plural': 'How It Works Steps',
                'ordering': ['order', 'step_number'],
            },
        ),
    ]
