# Generated by Django 6.1.1 on 2026-09-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_featureitem_herocontent_parallaxsection_processstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatingParallaxElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional reference title or label', max_length=100)),
                ('icon', models.CharField(default='fas fa-graduation-cap', help_text='FontAwesome icon class e.g. fas fa-book', max_length=100)),
                ('position_top', models.CharField(default='10%', help_text='Top CSS value (e.g. 10%, 50px, auto)', max_length=20)),
                ('position_left', models.CharField(default='10%', help_text='Left CSS value (e.g. 10%, 40px, auto)', max_length=20)),
                ('position_bottom', models.CharField(default='auto', help_text='Bottom CSS value (e.g. 15%, auto)', max_length=20)),
                ('position_right', models.CharField(default='auto', help_text='Right CSS value (e.g. 15%, auto)', max_length=20)),
                ('font_size', models.CharField(default='3rem', help_text='Icon font size (e.g. 2.5rem, 40px)', max_length=20)),
                ('opacity', models.FloatField(default=0.15, help_text='Opacity from 0.05 to 1.0')),
                ('animation_type', models.CharField(choices=[('float', 'Float Up & Down (Smooth)'), ('pulse', 'Pulse / Scale Glow'), ('rotate', 'Slow Rotation'), ('parallax', 'Scroll Parallax Shift')], default='float', max_length=30)),
                ('animation_duration', models.CharField(default='18s', help_text='Speed duration e.g. 15s, 20s', max_length=20)),
                ('animation_delay', models.CharField(default='0s', help_text='Delay offset e.g. 0s, 2s', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Floating Parallax Element',
                'verbose_name_plural': 'Floating Parallax Elements',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='herocontent',
            name='min_height',
            field=models.CharField(choices=[('medium', 'Medium (620px)'), ('large', 'Large (750px - Default)'), ('xlarge', 'Extra Large (850px)'), ('full', 'Full Screen (90vh)')], default='large', help_text='Hero section height sizing', max_length=20),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='overlay_color',
            field=models.CharField(default='#0f172a', help_text='Hex overlay color code e.g. #0f172a or #000000', max_length=30),
        ),
    ]
