# Generated by Django 6.1.1 on 2026-09-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_floatingparallaxelement_herocontent_min_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floatingparallaxelement',
            name='preset_position',
            field=models.CharField(choices=[('custom', 'Custom Coordinates (Enter Top/Left/Right/Bottom below)'), ('top_left', 'Top Left Corner (12% Top, 8% Left)'), ('top_right', 'Top Right Corner (20% Top, 12% Right)'), ('center_left', 'Center Left (48% Top, 10% Left)'), ('center_right', 'Center Right (50% Top, 8% Right)'), ('bottom_left', 'Bottom Left Corner (18% Bottom, 14% Left)'), ('bottom_right', 'Bottom Right Corner (22% Bottom, 20% Right)')], default='custom', help_text='Quick preset position location or custom coordinates', max_length=30),
        ),
        migrations.AddField(
            model_name='floatingparallaxelement',
            name='section_target',
            field=models.CharField(choices=[('hero', 'Hero Section (Top of Page)'), ('parallax', 'Parallax Showcase Banners'), ('all', 'All Hero & Parallax Sections')], default='hero', help_text='Select section where this icon appears on homepage', max_length=30),
        ),
    ]
