# Generated by Django 6.1.1 on 2026-09-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_floatingparallaxelement_preset_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parallaxsection',
            name='target_position',
            field=models.CharField(choices=[('after_hero', 'After Hero Section'), ('after_stats', 'After Stats Section'), ('after_process', 'After How It Works / Stepper'), ('after_features', 'After Comprehensive Features'), ('after_cta', 'After CTA Section (Before Footer)')], default='after_process', help_text='Where on the home page this parallax section appears', max_length=30),
        ),
        migrations.AlterField(
            model_name='parallaxsection',
            name='badge_text',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
