# Generated by Django 6.1.1 on 2026-09-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_parallaxsection_target_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herocontent',
            name='bg_color',
            field=models.CharField(blank=True, default='#0f172a', help_text='Hex code or CSS color', max_length=30),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='bg_gradient',
            field=models.CharField(blank=True, default='linear-gradient(135deg, #0f172a 0%, #1e3a5f 50%, #164e63 100%)', help_text='Custom CSS gradient string', max_length=255),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='bg_type',
            field=models.CharField(blank=True, choices=[('gradient', 'Modern Dark Gradient'), ('color', 'Solid Color'), ('image', 'Background Image with Overlay')], default='gradient', max_length=20),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='min_height',
            field=models.CharField(choices=[('compact', 'Compact (500px)'), ('medium', 'Medium (620px)'), ('large', 'Large (750px - Default)'), ('xlarge', 'Extra Large (850px)'), ('full', 'Full Screen (90vh)')], default='large', help_text='Hero section height sizing', max_length=20),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='overlay_color',
            field=models.CharField(blank=True, default='#0f172a', help_text='Hex overlay color code e.g. #0f172a or #000000', max_length=30),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='overlay_opacity',
            field=models.FloatField(blank=True, default=0.85, help_text='Overlay darkness from 0.0 (transparent) to 1.0 (solid)'),
        ),
    ]
