# Generated by Django 6.1.1 on 2026-10-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_alter_herocontent_bg_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FloatingParallaxElement',
        ),
        migrations.AlterModelOptions(
            name='featureitem',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Feature Module', 'verbose_name_plural': 'Feature Modules'},
        ),
        migrations.AddField(
            model_name='featureitem',
            name='badge',
            field=models.CharField(blank=True, default='', help_text='Badge tag e.g. Academics, Kenyan CBC, Finance', max_length=50),
        ),
        migrations.AddField(
            model_name='featureitem',
            name='category',
            field=models.CharField(choices=[('academic', 'Academics & CBC'), ('finance', 'Finance & M-Pesa'), ('operations', 'Operations & Logistics'), ('admin', 'Administration & HR'), ('ai', 'AI & Communication')], default='academic', max_length=30),
        ),
        migrations.AddField(
            model_name='featureitem',
            name='feature_points',
            field=models.TextField(blank=True, default='', help_text='Key features/highlights, one per line'),
        ),
        migrations.AlterField(
            model_name='featureitem',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='page',
            field=models.CharField(choices=[('about', 'About Us'), ('home_hero', 'Home - Hero Section'), ('contact', 'Contact Info'), ('policy', 'Privacy Policy'), ('terms', 'Terms of Service'), ('features', 'Features')], max_length=50, unique=True),
        ),
    ]
