# Generated by Django 4.2.7 on 2025-11-13 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('academics', '0004_class_school_subject_school'),
        ('students', '0001_initial'),
        ('core', '0002_add_admission_number_prefix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now, verbose_name='Assigned Date')),
                ('due_date', models.DateTimeField(verbose_name='Due Date')),
                ('points', models.DecimalField(decimal_places=2, default=100, max_digits=6, verbose_name='Points')),
                ('grading_type', models.CharField(choices=[('points', 'Points'), ('letter', 'Letter Grade'), ('pass_fail', 'Pass/Fail')], default='points', max_length=20, verbose_name='Grading Type')),
                ('is_graded', models.BooleanField(default=True, verbose_name='Is Graded')),
                ('submission_type', models.CharField(choices=[('text', 'Text Entry'), ('file', 'File Upload'), ('both', 'Text & File'), ('link', 'Link/URL'), ('none', 'No Online Submission')], default='both', max_length=10, verbose_name='Submission Type')),
                ('allow_late_submissions', models.BooleanField(default=True, verbose_name='Allow Late Submissions')),
                ('late_penalty_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Late Penalty (%)')),
                ('max_attempts', models.PositiveSmallIntegerField(default=1, help_text='0 for unlimited attempts', verbose_name='Maximum Attempts')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='homework/attachments/', verbose_name='Attachment')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_assignments', to='core.academicyear')),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_assignments', to='academics.class')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_homework', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework_assignments', to='tenants.school')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework_assignments', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_assignments', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Homework Assignment',
                'verbose_name_plural': 'Homework Assignments',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(blank=True, verbose_name='Submission Text')),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='homework/submissions/', verbose_name='Submission File')),
                ('submission_url', models.URLField(blank=True, verbose_name='Submission URL')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('late', 'Late Submission'), ('graded', 'Graded'), ('returned', 'Returned')], default='draft', max_length=20, verbose_name='Status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, verbose_name='Attempt Number')),
                ('is_late', models.BooleanField(default=False, verbose_name='Is Late')),
                ('points_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Points Earned')),
                ('grade', models.CharField(blank=True, max_length=10, verbose_name='Grade')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Graded At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework_graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.homeworkassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='students.student')),
            ],
            options={
                'verbose_name': 'Homework Submission',
                'verbose_name_plural': 'Homework Submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('homework', 'student', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='HomeworkResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Resource Title')),
                ('resource_type', models.CharField(choices=[('document', 'Document'), ('presentation', 'Presentation'), ('worksheet', 'Worksheet'), ('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('link', 'Web Link'), ('other', 'Other')], max_length=20, verbose_name='Resource Type')),
                ('file', models.FileField(blank=True, null=True, upload_to='homework/resources/', verbose_name='File')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_homework_resources', to=settings.AUTH_USER_MODEL)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='homework.homeworkassignment')),
            ],
            options={
                'verbose_name': 'Homework Resource',
                'verbose_name_plural': 'Homework Resources',
            },
        ),
        migrations.CreateModel(
            name='HomeworkComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_comments', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='homework.homeworksubmission')),
            ],
            options={
                'verbose_name': 'Homework Comment',
                'verbose_name_plural': 'Homework Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
