# Generated by Django 4.2.7 on 2025-12-08 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('club_type', models.CharField(choices=[('academic', 'Academic'), ('sports', 'Sports'), ('arts', 'Arts & Culture'), ('service', 'Service & Leadership'), ('technology', 'Technology'), ('religious', 'Religious'), ('social', 'Social & Welfare')], max_length=20)),
                ('meeting_day', models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('meeting_venue', models.CharField(blank=True, max_length=100)),
                ('max_members', models.PositiveIntegerField(default=50, help_text='Maximum number of members')),
                ('membership_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('requires_application', models.BooleanField(default=True, help_text='Students must apply to join')),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='tenants.school')),
                ('student_president', models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president_clubs', to=settings.AUTH_USER_MODEL)),
                ('student_secretary', models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_clubs', to=settings.AUTH_USER_MODEL)),
                ('teacher_advisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_clubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClubActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(choices=[('meeting', 'Regular Meeting'), ('event', 'Special Event'), ('competition', 'Competition'), ('workshop', 'Workshop'), ('community_service', 'Community Service'), ('fundraiser', 'Fundraiser'), ('trip', 'Field Trip'), ('other', 'Other')], max_length=20)),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField(help_text='Duration of the activity')),
                ('venue', models.CharField(max_length=200)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('points_awarded', models.PositiveIntegerField(default=0, help_text='Club points for participation')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='clubs.club')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ClubResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('image', 'Image'), ('link', 'Link'), ('other', 'Other')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='clubs/resources/')),
                ('url', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=True, help_text='Available to all members')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='clubs.club')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('competition', 'Competition'), ('award', 'Award'), ('recognition', 'Recognition'), ('project', 'Project'), ('other', 'Other')], max_length=20)),
                ('date_achieved', models.DateField()),
                ('level', models.CharField(help_text='e.g., School, Regional, National', max_length=50)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='clubs/achievements/')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='clubs/achievements/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='clubs.club')),
                ('participants', models.ManyToManyField(blank=True, related_name='club_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_achieved'],
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('application_reason', models.TextField(help_text='Why do you want to join this club?')),
                ('parent_consent', models.BooleanField(default=False, help_text='Parent consent obtained')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated')], default='pending', max_length=20)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('position_held', models.CharField(blank=True, help_text='e.g., Member, Treasurer, etc.', max_length=50)),
                ('fee_paid', models.BooleanField(default=False)),
                ('fee_paid_date', models.DateField(blank=True, null=True)),
                ('fee_amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clubs.club')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-application_date'],
                'unique_together': {('student', 'club')},
            },
        ),
        migrations.CreateModel(
            name='ClubAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=10)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='clubs.clubactivity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('activity', 'student')},
            },
        ),
    ]
