# Generated by Django 4.2.7 on 2025-12-08 08:32

from django.db import migrations

def create_kenyan_school_clubs(apps, schema_editor):
    """
    Populate the database with typical clubs found in Kenyan schools
    """
    Club = apps.get_model('clubs', 'Club')
    School = apps.get_model('tenants', 'School')
    
    # Get the first school (or you can make this more specific)
    school = School.objects.first()
    if not school:
        return
    
    # Academic Clubs
    academic_clubs = [
        {
            'name': 'Mathematics Club',
            'description': 'Enhance mathematical skills through problem-solving, competitions, and collaborative learning.',
            'club_type': 'academic',
            'meeting_day': 'wednesday',
            'meeting_time': '16:00:00',
            'meeting_venue': 'Mathematics Laboratory',
            'max_members': 30,
            'membership_fee': 200.00,
            'requires_application': True,
        },
        {
            'name': 'Science Club',
            'description': 'Explore scientific concepts through experiments, research projects, and science fairs.',
            'club_type': 'academic',
            'meeting_day': 'thursday',
            'meeting_time': '16:00:00',
            'meeting_venue': 'Science Laboratory',
            'max_members': 40,
            'membership_fee': 300.00,
            'requires_application': True,
        },
        {
            'name': 'Debate Club',
            'description': 'Develop public speaking, critical thinking, and argumentation skills through debates and discussions.',
            'club_type': 'academic',
            'meeting_day': 'tuesday',
            'meeting_time': '16:30:00',
            'meeting_venue': 'Assembly Hall',
            'max_members': 25,
            'membership_fee': 150.00,
            'requires_application': True,
        },
        {
            'name': 'Journalism Club',
            'description': 'Produce school newspaper, develop writing skills, and cover school events.',
            'club_type': 'academic',
            'meeting_day': 'friday',
            'meeting_time': '15:30:00',
            'meeting_venue': 'Computer Lab',
            'max_members': 20,
            'membership_fee': 250.00,
            'requires_application': True,
        },
    ]
    
    # Sports Clubs
    sports_clubs = [
        {
            'name': 'Football Club',
            'description': 'Develop football skills, teamwork, and compete in inter-school tournaments.',
            'club_type': 'sports',
            'meeting_day': 'monday',
            'meeting_time': '16:00:00',
            'meeting_venue': 'School Field',
            'max_members': 25,
            'membership_fee': 500.00,
            'requires_application': False,
        },
        {
            'name': 'Basketball Club',
            'description': 'Learn basketball fundamentals, practice teamwork, and participate in competitions.',
            'club_type': 'sports',
            'meeting_day': 'wednesday',
            'meeting_time': '16:00:00',
            'meeting_venue': 'Basketball Court',
            'max_members': 20,
            'membership_fee': 400.00,
            'requires_application': False,
        },
        {
            'name': 'Volleyball Club',
            'description': 'Develop volleyball skills and sportsmanship through regular practice and matches.',
            'club_type': 'sports',
            'meeting_day': 'tuesday',
            'meeting_time': '16:30:00',
            'meeting_venue': 'Volleyball Court',
            'max_members': 18,
            'membership_fee': 350.00,
            'requires_application': False,
        },
        {
            'name': 'Athletics Club',
            'description': 'Track and field training for various athletic events and competitions.',
            'club_type': 'sports',
            'meeting_day': 'thursday',
            'meeting_time': '16:00:00',
            'meeting_venue': 'School Track',
            'max_members': 30,
            'membership_fee': 300.00,
            'requires_application': False,
        },
    ]
    
    # Arts & Culture Clubs
    arts_clubs = [
        {
            'name': 'Drama Club',
            'description': 'Develop acting skills, stage presence, and produce theatrical performances.',
            'club_type': 'arts',
            'meeting_day': 'tuesday',
            'meeting_time': '16:00:00',
            'meeting_venue': 'School Auditorium',
            'max_members': 30,
            'membership_fee': 250.00,
            'requires_application': True,
        },
        {
            'name': 'Music Club',
            'description': 'Learn musical instruments, vocal training, and participate in musical performances.',
            'club_type': 'arts',
            'meeting_day': 'wednesday',
            'meeting_time': '16:00:00',
            'meeting_venue': 'Music Room',
            'max_members': 35,
            'membership_fee': 300.00,
            'requires_application': True,
        },
        {
            'name': 'Dance Club',
            'description': 'Learn various dance styles including traditional Kenyan dances and modern choreography.',
            'club_type': 'arts',
            'meeting_day': 'thursday',
            'meeting_time': '16:30:00',
            'meeting_venue': 'Dance Studio',
            'max_members': 25,
            'membership_fee': 200.00,
            'requires_application': True,
        },
    ]
    
    # Service & Leadership Clubs
    service_clubs = [
        {
            'name': 'Scouts Movement',
            'description': 'Develop leadership skills, outdoor survival, and community service through scouting activities.',
            'club_type': 'service',
            'meeting_day': 'saturday',
            'meeting_time': '09:00:00',
            'meeting_venue': 'Scouts Ground',
            'max_members': 40,
            'membership_fee': 400.00,
            'requires_application': True,
        },
        {
            'name': 'Interact Club',
            'description': 'Rotary-sponsored club focusing on community service and leadership development.',
            'club_type': 'service',
            'meeting_day': 'wednesday',
            'meeting_time': '16:00:00',
            'meeting_venue': 'Conference Room',
            'max_members': 30,
            'membership_fee': 200.00,
            'requires_application': True,
        },
        {
            'name': 'Environmental Club',
            'description': 'Promote environmental conservation, tree planting, and sustainable practices.',
            'club_type': 'service',
            'meeting_day': 'friday',
            'meeting_time': '15:30:00',
            'meeting_venue': 'School Garden',
            'max_members': 35,
            'membership_fee': 100.00,
            'requires_application': False,
        },
    ]
    
    # Technology Clubs
    tech_clubs = [
        {
            'name': 'Computer Club',
            'description': 'Learn programming, web development, and computer literacy skills.',
            'club_type': 'technology',
            'meeting_day': 'thursday',
            'meeting_time': '16:00:00',
            'meeting_venue': 'Computer Lab',
            'max_members': 30,
            'membership_fee': 250.00,
            'requires_application': False,
        },
        {
            'name': 'Robotics Club',
            'description': 'Design, build, and program robots for competitions and learning.',
            'club_type': 'technology',
            'meeting_day': 'friday',
            'meeting_time': '15:30:00',
            'meeting_venue': 'Science Laboratory',
            'max_members': 20,
            'membership_fee': 500.00,
            'requires_application': True,
        },
    ]
    
    # Religious Clubs
    religious_clubs = [
        {
            'name': 'Christian Union',
            'description': 'Fellowship, Bible study, and spiritual growth for Christian students.',
            'club_type': 'religious',
            'meeting_day': 'friday',
            'meeting_time': '16:00:00',
            'meeting_venue': 'Chapel',
            'max_members': 50,
            'membership_fee': 100.00,
            'requires_application': False,
        },
        {
            'name': 'Muslim Students Association',
            'description': 'Islamic teachings, prayers, and cultural activities for Muslim students.',
            'club_type': 'religious',
            'meeting_day': 'friday',
            'meeting_time': '13:00:00',
            'meeting_venue': 'Prayer Room',
            'max_members': 40,
            'membership_fee': 100.00,
            'requires_application': False,
        },
    ]
    
    # Combine all clubs
    all_clubs = (
        academic_clubs + sports_clubs + arts_clubs + 
        service_clubs + tech_clubs + religious_clubs
    )
    
    # Create clubs
    for club_data in all_clubs:
        Club.objects.create(school=school, **club_data)

def reverse_kenyan_school_clubs(apps, schema_editor):
    """
    Remove the created clubs
    """
    Club = apps.get_model('clubs', 'Club')
    School = apps.get_model('tenants', 'School')
    
    school = School.objects.first()
    if school:
        Club.objects.filter(school=school).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_kenyan_school_clubs, reverse_kenyan_school_clubs),
    ]
