# Generated by Django 4.2.7 on 2025-12-08 08:32

from django.db import migrations


def create_kenyan_school_clubs(apps, schema_editor):
    """
    Populate clubs via sample_data script rather than migration
    to prevent cross-database router conflicts and NOT NULL constraint violations.
    """
    pass


def reverse_kenyan_school_clubs(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_kenyan_school_clubs, reverse_kenyan_school_clubs),
    ]
