# Generated by Django 6.1.1 on 2026-09-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_populate_kenyan_clubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='is_sample_data',
            field=models.BooleanField(default=False),
        ),
    ]
