# Generated by Django 4.2.7 on 2025-11-05 07:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Coupon Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Value')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max Discount')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(verbose_name='Valid Until')),
                ('max_uses', models.IntegerField(default=0, verbose_name='Max Uses')),
                ('max_uses_per_user', models.IntegerField(default=1, verbose_name='Max Uses Per User')),
                ('times_used', models.IntegerField(default=0, verbose_name='Times Used')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Payment ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Currency')),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('razorpay', 'Razorpay'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=20, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Status')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction ID')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='Gateway Response')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Invoice Number')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Invoice Date')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('plan_type', models.CharField(choices=[('free_trial', 'Free Trial'), ('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=20, verbose_name='Plan Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly')], max_length=20, verbose_name='Billing Cycle')),
                ('trial_days', models.IntegerField(default=0, verbose_name='Trial Days')),
                ('max_students', models.IntegerField(default=100, verbose_name='Max Students')),
                ('max_teachers', models.IntegerField(default=20, verbose_name='Max Teachers')),
                ('max_staff', models.IntegerField(default=10, verbose_name='Max Staff')),
                ('max_branches', models.IntegerField(default=1, verbose_name='Max Branches')),
                ('storage_limit_gb', models.IntegerField(default=5, verbose_name='Storage Limit (GB)')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='Features')),
                ('enable_online_exam', models.BooleanField(default=True, verbose_name='Enable Online Exam')),
                ('enable_online_payment', models.BooleanField(default=True, verbose_name='Enable Online Payment')),
                ('enable_chat', models.BooleanField(default=True, verbose_name='Enable Chat')),
                ('enable_sms', models.BooleanField(default=False, verbose_name='Enable SMS')),
                ('enable_library', models.BooleanField(default=True, verbose_name='Enable Library')),
                ('enable_transport', models.BooleanField(default=True, verbose_name='Enable Transport')),
                ('enable_dormitory', models.BooleanField(default=True, verbose_name='Enable Dormitory')),
                ('enable_inventory', models.BooleanField(default=True, verbose_name='Enable Inventory')),
                ('enable_hr', models.BooleanField(default=True, verbose_name='Enable HR Management')),
                ('enable_reports', models.BooleanField(default=True, verbose_name='Enable Advanced Reports')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Is Popular')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='pending', max_length=20, verbose_name='Status')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Auto Renew')),
                ('is_trial', models.BooleanField(default=False, verbose_name='Is Trial')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
