# Generated by Django 4.2.7 on 2025-11-05 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_plans',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='subscriptions.subscriptionplan'),
        ),
    ]
