# Generated by Django 4.2.7 on 2025-12-01 08:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_type', models.CharField(choices=[('new', 'New Subscription'), ('renewal', 'Subscription Renewal'), ('upgrade', 'Plan Upgrade'), ('trial_end', 'Trial End')], default='new', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('billing_start_date', models.DateField(blank=True, null=True)),
                ('billing_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='subscriptions.payment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.school')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', '-created_at'], name='subscriptio_school__57d949_idx'), models.Index(fields=['invoice_number'], name='subscriptio_invoice_50e7d3_idx'), models.Index(fields=['status'], name='subscriptio_status_10461a_idx')],
            },
        ),
    ]
