# Generated by Django 4.2.7 on 2026-01-13 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_payment_account_name_payment_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='data_migration_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Data Migration Fee'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='license_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='License Fee'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='setup_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='One-time Setup Fee'),
        ),
    ]
