# Generated by Django 4.2.7 on 2026-01-13 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscriptionplan_data_migration_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='training_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Training Fee'),
        ),
    ]
