# Generated by Django 4.2.7 on 2026-01-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscriptionplan_training_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='overdue_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
