# Generated by Django 4.2.7 on 2026-01-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_invoice_due_reminder_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa_paybill', 'M-Pesa Paybill'), ('mpesa_stk', 'M-Pesa STK Push'), ('mpesa_buygoods', 'M-Pesa Buy Goods & Services'), ('mpesa_send_money', 'M-Pesa Send Money'), ('mpesa_pochi', 'M-Pesa Pochi la Biashara'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=20, verbose_name='Payment Method'),
        ),
    ]
