# Generated by Django 4.2.7 on 2026-02-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_staff',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_teachers',
        ),
        migrations.AddField(
            model_name='invoice',
            name='pre_due_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('termly', 'Termly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly')], max_length=20, verbose_name='Billing Cycle'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_students',
            field=models.IntegerField(default=0, verbose_name='Max Students'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=20, verbose_name='Plan Type'),
        ),
    ]
