# Generated by Django 6.1.1 on 2026-10-07 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_remove_subscriptionplan_max_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('termly', 'Termly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly')], default='termly', max_length=20, verbose_name='Billing Cycle'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount Applied'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Period Discount (%)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='yearly_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Yearly Discount (%)'),
        ),
    ]
