# Generated by Django 4.2.7 on 2025-11-09 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('students', '0001_initial'),
        ('dormitory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dormitories', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.IntegerField(blank=True, default=1, verbose_name='Floor Number'),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(blank=True, max_length=20, verbose_name='Bed Number')),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Dormitory Fee')),
                ('start_date', models.DateField(verbose_name='Allocation Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Allocation End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='dormitory.room')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_allocation', to='students.student')),
            ],
            options={
                'verbose_name': 'Room Allocation',
                'verbose_name_plural': 'Room Allocations',
                'ordering': ['room', 'student'],
            },
        ),
    ]
