# Generated by Django 6.1.1 on 2026-09-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0002_dormitory_address_dormitory_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='is_sample_data',
            field=models.BooleanField(default=False, verbose_name='Is Sample Data'),
        ),
    ]
