# Generated by Django 4.2.7 on 2025-11-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Assigned Subject',
                'verbose_name_plural': 'Assigned Subjects',
                'ordering': ['class_name', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Assignment Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('assignment_file', models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='Assignment File')),
                ('assigned_date', models.DateField(verbose_name='Assigned Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('max_marks', models.IntegerField(default=100, verbose_name='Maximum Marks')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_file', models.FileField(upload_to='assignment_submissions/', verbose_name='Submission File')),
                ('submission_text', models.TextField(blank=True, verbose_name='Submission Text')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Marks Obtained')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='Evaluated At')),
                ('is_late', models.BooleanField(default=False, verbose_name='Is Late Submission')),
            ],
            options={
                'verbose_name': 'Assignment Submission',
                'verbose_name_plural': 'Assignment Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Class Name')),
                ('numeric_name', models.IntegerField(blank=True, null=True, verbose_name='Numeric Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['order', 'numeric_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Room Name')),
                ('room_number', models.CharField(max_length=50, unique=True, verbose_name='Room Number')),
                ('room_type', models.CharField(choices=[('lecture', 'Lecture Hall'), ('lab', 'Laboratory'), ('computer', 'Computer Lab'), ('library', 'Library'), ('auditorium', 'Auditorium'), ('other', 'Other')], max_length=20, verbose_name='Room Type')),
                ('capacity', models.IntegerField(default=40, verbose_name='Capacity')),
                ('floor', models.CharField(blank=True, max_length=20, verbose_name='Floor')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='Building')),
                ('has_projector', models.BooleanField(default=False, verbose_name='Has Projector')),
                ('has_ac', models.BooleanField(default=False, verbose_name='Has AC')),
                ('has_smartboard', models.BooleanField(default=False, verbose_name='Has Smart Board')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'ordering': ['building', 'floor', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='ClassRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Day of Week')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Class Routine',
                'verbose_name_plural': 'Class Routines',
                'ordering': ['day_of_week', 'class_time__start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Period Name')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('is_break', models.BooleanField(default=False, verbose_name='Is Break')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Class Time',
                'verbose_name_plural': 'Class Times',
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='House Name')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='House Color')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('total_points', models.IntegerField(default=0, verbose_name='Total Points')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OptionalSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Optional Subject',
                'verbose_name_plural': 'Optional Subjects',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Section Name')),
                ('max_students', models.IntegerField(default=40, verbose_name='Maximum Students')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['class_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content_type', models.CharField(choices=[('assignment', 'Assignment'), ('syllabus', 'Syllabus'), ('notes', 'Notes'), ('video', 'Video'), ('other', 'Other Downloads')], max_length=20, verbose_name='Content Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='study_materials/', verbose_name='File')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='File Type')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is Public')),
                ('available_from', models.DateField(blank=True, null=True, verbose_name='Available From')),
                ('available_until', models.DateField(blank=True, null=True, verbose_name='Available Until')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('download_count', models.IntegerField(default=0, verbose_name='Download Count')),
            ],
            options={
                'verbose_name': 'Study Material',
                'verbose_name_plural': 'Study Materials',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Subject Code')),
                ('subject_type', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical'), ('both', 'Theory + Practical')], default='theory', max_length=20, verbose_name='Subject Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('credits', models.IntegerField(default=0, verbose_name='Credits')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('content', models.TextField(verbose_name='Syllabus Content')),
                ('file', models.FileField(blank=True, null=True, upload_to='syllabus/', verbose_name='Syllabus File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Syllabus',
                'verbose_name_plural': 'Syllabi',
                'ordering': ['-created_at'],
            },
        ),
    ]
