# Generated by Django 4.2.7 on 2025-12-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_class_school_subject_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='education_level',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('pre_primary', 'Pre-Primary'), ('lower_primary', 'Lower Primary (Grades 1-3)'), ('upper_primary', 'Upper Primary (Grades 4-6)'), ('junior_secondary', 'Junior Secondary (Grades 7-9)'), ('senior_secondary', 'Senior Secondary (Grades 10-12)'), ('tvet', 'TVET'), ('college', 'College')], default='unspecified', max_length=50, verbose_name='Education Level'),
        ),
    ]
