# Generated by Django 4.2.7 on 2025-11-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Route Name')),
                ('route_number', models.CharField(max_length=50, unique=True, verbose_name='Route Number')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('fare', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fare')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['route_number'],
            },
        ),
    ]
