# Generated by Django 4.2.7 on 2025-11-09 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Stop Name')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('stop_order', models.IntegerField(verbose_name='Stop Order')),
                ('pickup_time', models.TimeField(verbose_name='Pickup Time')),
                ('dropoff_time', models.TimeField(verbose_name='Drop-off Time')),
                ('fare_from_start', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fare from Start')),
            ],
            options={
                'verbose_name': 'Route Stop',
                'verbose_name_plural': 'Route Stops',
                'ordering': ['route', 'stop_order'],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Distance (km)'),
        ),
        migrations.AddField(
            model_name='route',
            name='end_place',
            field=models.CharField(blank=True, max_length=200, verbose_name='End Place'),
        ),
        migrations.AddField(
            model_name='route',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_routes', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='route',
            name='start_place',
            field=models.CharField(blank=True, max_length=200, verbose_name='Start Place'),
        ),
        migrations.AddField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='route',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monthly Fare'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Route Number'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50, verbose_name='Vehicle Number')),
                ('vehicle_model', models.CharField(max_length=100, verbose_name='Vehicle Model')),
                ('vehicle_type', models.CharField(choices=[('bus', 'Bus'), ('van', 'Van'), ('minibus', 'Minibus'), ('car', 'Car')], default='bus', max_length=20, verbose_name='Vehicle Type')),
                ('capacity', models.IntegerField(verbose_name='Seating Capacity')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='Registration Number')),
                ('insurance_expiry', models.DateField(blank=True, null=True, verbose_name='Insurance Expiry')),
                ('fitness_certificate_expiry', models.DateField(blank=True, null=True, verbose_name='Fitness Certificate Expiry')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='transport.route')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='tenants.school')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['vehicle_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Transport Fee')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='transport.route')),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='transport.routestop')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='students.student')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='transport.vehicle')),
            ],
            options={
                'verbose_name': 'Student Transport',
                'verbose_name_plural': 'Student Transport Assignments',
                'ordering': ['route', 'stop__stop_order'],
            },
        ),
        migrations.AddField(
            model_name='routestop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transport.route'),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Driver Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('license_number', models.CharField(max_length=100, verbose_name='License Number')),
                ('license_expiry', models.DateField(verbose_name='License Expiry')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='tenants.school')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='transport.vehicle')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'stop_order')},
        ),
    ]
