# Generated by Django 4.2.7 on 2025-11-09 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('academics', '0003_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave_management', '0002_leave_staff_alter_leave_applicant_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Attendance Date')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('sick', 'Sick')], default='present', max_length=20, verbose_name='Status')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.class')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='tenants.school')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Attendance',
                'verbose_name_plural': 'Student Attendance Records',
                'ordering': ['-date', 'student__admission_number'],
                'indexes': [models.Index(fields=['date', 'status'], name='attendance__date_514473_idx'), models.Index(fields=['student', 'date'], name='attendance__student_0335ea_idx')],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Attendance Date')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('on_leave', 'On Leave'), ('half_day', 'Half Day')], default='present', max_length=20, verbose_name='Status')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='Check In Time')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='Check Out Time')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('leave_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='leave_management.leave')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_staff_attendance', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance', to='tenants.school')),
                ('staff', models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'admin', 'staff']}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Attendance',
                'verbose_name_plural': 'Staff Attendance Records',
                'ordering': ['-date', 'staff__first_name'],
                'indexes': [models.Index(fields=['date', 'status'], name='attendance__date_3dbb50_idx'), models.Index(fields=['staff', 'date'], name='attendance__staff_i_d77b2d_idx')],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
