# Generated by Django 4.2.7 on 2025-11-19 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examinations', '0003_examsubmission_questionanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_graded_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
