# Generated by Django 4.2.7 on 2026-01-12 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_school_institution_type'),
        ('examinations', '0004_alter_examsubmission_graded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='tenants.school'),
        ),
    ]
