# Generated by Django 4.2.7 on 2026-03-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0006_grade_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='exam_attachments/'),
        ),
    ]
