# Generated by Django 4.2.7 on 2026-03-10 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_classroom_school_classroutine_school_and_more'),
        ('examinations', '0007_exam_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_configs', to='examinations.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subject_configs', to='academics.subject')),
            ],
            options={
                'ordering': ['subject_id'],
                'unique_together': {('exam', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='multi_subject_exams', through='examinations.ExamSubjectConfig', to='academics.subject'),
        ),
    ]
