# Generated by Django 6.1.1 on 2026-09-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0008_examsubjectconfig_exam_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_sample_data',
            field=models.BooleanField(default=False),
        ),
    ]
